const user=JSON.parse(localStorage.getItem("lifeSpecupUser")||"{}");
const state=JSON.parse(localStorage.getItem("lifeSpecupState")||'{"xp":0,"history":[]}');
const finance=JSON.parse(localStorage.getItem("lifeSpecupFinance")||'{}');
const questState=JSON.parse(localStorage.getItem("lifeSpecupQuests")||'{"selected":[],"completed":{}}');
const fmt=n=>Math.round(Number(n)||0).toLocaleString("ko-KR")+"원";
function levelInfo(xp){let level=1,need=100,spent=0;while(xp-spent>=need){spent+=need;level++;need=100+(level-1)*25}return{level,cur:xp-spent,need,pct:Math.min(100,(xp-spent)/need*100)}}
function calcFinance(){let deposits=(finance.deposits||[]).reduce((s,x)=>s+(+x.amount||0),0),stocks=(finance.stocks||[]).reduce((s,x)=>s+(+x.amount||0),0),housing=(finance.housing||[]).reduce((s,x)=>s+(+x.assetValue||0)+(+x.deposit||0),0),debts=(finance.debts||[]).reduce((s,x)=>s+(+x.balance||0),0),fixed=(finance.expenses||[]).reduce((s,x)=>s+(+x.amount||0),0),loanPay=(finance.debts||[]).reduce((s,x)=>s+(+x.monthly||0),0),housingPay=(finance.housing||[]).reduce((s,x)=>s+(+x.monthlyRent||0),0),savingPay=(finance.deposits||[]).reduce((s,x)=>s+(+x.monthlySaving||0),0)+(finance.stocks||[]).reduce((s,x)=>s+(+x.monthlyInvest||0),0);return{assets:deposits+stocks+housing,debts,net:deposits+stocks+housing-debts,fixed,loanPay,housingPay,savingPay}}
const li=levelInfo(state.xp||0),f=calcFinance();userName.textContent=user.nickname||"플레이어";avatar.textContent=(user.nickname||"U")[0];topLevel.textContent=lifeLevel.textContent=li.level;xpLabel.textContent=`${li.cur} / ${li.need} XP`;progressText.textContent=Math.floor(li.pct)+"%";levelProgress.style.width=li.pct+"%";
const rewards={2:"퀘스트 슬롯 +1",3:"7일 연속 기록 배지",5:"주간 성장 리포트 해금",10:"커리어 비교 분석 해금",15:"월간 성장 회고 해금",20:"커스텀 퀘스트 보너스"};
let next=Object.keys(rewards).map(Number).find(x=>x>li.level)||25;nextReward.textContent=`LV.${next} 달성 시: ${rewards[next]||"성장 마일스톤 배지"}`;
const certs=user.certificates||[];let certScore=Math.min(100,certs.reduce((s,c)=>s+({D:2,"D+":3,C:4,"C+":5,"B-":6,B:7,"B+":8,"A-":9,A:10,"A+":12,S:14,"S+":16}[c.personal||c.base]||4),0));
const financeScore=f.net<=0?Math.max(10,40+f.net/1000000*3):Math.min(100,45+Math.log10(1+f.net/1000000)*18);
const stats=[["💼","커리어",Math.round(Math.min(100,35+certScore*.45))],["🏆","자격 경쟁력",Math.round(certScore)],["💰","재정 안정",Math.round(financeScore)],["🔥","실천력",Math.min(100,Math.round((state.xp||0)/10))]];
stats.forEach(s=>{statsEl=document.querySelector("#stats");statsEl.insertAdjacentHTML("beforeend",`<article class="card stat"><div class="stat-top"><span>${s[0]} ${s[1]}</span></div><div class="stat-value">${s[2]}</div><div class="progress"><div style="width:${s[2]}%"></div></div></article>`)});
goal.textContent=user.goalJob||"미설정";track.textContent=[user.companyType,user.track].filter(Boolean).join(" · ")||"미설정";assets.textContent=fmt(f.assets);debts.textContent=fmt(f.debts);net.textContent=fmt(f.net);fixed.textContent=fmt(f.fixed);loanPay.textContent=fmt(f.loanPay);housingPay.textContent=fmt(f.housingPay);savingPay.textContent=fmt(f.savingPay);
Object.entries(rewards).forEach(([lv,r])=>unlocks.insertAdjacentHTML("beforeend",`<div class="unlock ${li.level>=+lv?"":"locked"}"><span>LV.${lv} ${r}</span><b>${li.level>=+lv?"해금":"🔒"}</b></div>`));
function lifeDay(d=new Date()){let x=new Date(d);if(x.getHours()<6)x.setDate(x.getDate()-1);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`}
const today=lifeDay();let selected=questState.selected||[],dayData=questState.days?.[today],done=dayData?.completed||questState.completed?.[today]||[];todayQuests.innerHTML=selected.length?selected.slice(0,5).map(q=>`<div class="quest-item ${done.includes(q.id)?"done":""}"><div><b class="qname">${q.name}</b><div class="muted">${q.detail}${q.type==="daily"?" · 하루 종료 후 판정":""}</div></div><span class="xp">+${q.xp} XP</span></div>`).join(""):'<p class="sub">아직 일일 퀘스트를 고르지 않았습니다.</p><button class="primary" onclick="location.href=\'quests.html\'">퀘스트 고르기</button>';
history.innerHTML=(state.history||[]).slice(0,5).map(h=>`<div class="history-row"><span>${h.text}</span><b>+${h.xp} XP</b></div>`).join("")||'<p class="sub">첫 퀘스트를 완료하면 여기에 기록됩니다.</p>';
const slides=[
["레벨은 당신의 '가치'가 아닙니다","LV은 현실에서 얼마나 꾸준히 행동했는지를 보여주는 플레이어 레벨입니다.",`<div class="tutorial-level">LV.${li.level}</div><p>자산·학력·직업이 높다고 자동으로 레벨이 오르지 않습니다.<br>공부, 운동, 재정관리 같은 실제 행동으로 XP를 얻습니다.</p>`],
["현재 상태는 따로 봅니다","커리어·자격·재정 같은 현실 상태는 별도의 스탯으로 표시합니다.",`<div class="summary-cards"><div class="card summary-card"><small>커리어</small><b>${stats[0][2]}</b></div><div class="card summary-card"><small>재정</small><b>${stats[2][2]}</b></div></div>`],
["퀘스트로 XP를 얻습니다","공부 1시간, 운동 30분처럼 미리 고른 행동을 완료하면 그날 XP가 쌓입니다.",`<h3>📚 공부 1시간 <span class="xp">+20 XP</span></h3><h3>💪 운동 30분 <span class="xp">+15 XP</span></h3>`],
["레벨업에는 실제 기능 보상이 있습니다","레벨이 오르면 기록과 분석 기능이 단계적으로 열립니다. 숫자만 바뀌는 레벨은 만들지 않습니다.",`<div class="unlocks"><div class="unlock"><span>LV.2 퀘스트 슬롯 +1</span><b>🎁</b></div><div class="unlock locked"><span>LV.5 주간 성장 리포트</span><b>🔒</b></div></div>`]
];let si=0;function drawT(){tStep.textContent=`${si+1} / ${slides.length}`;tTitle.textContent=slides[si][0];tText.textContent=slides[si][1];tArt.innerHTML=slides[si][2];dots.innerHTML=slides.map((_,i)=>`<span class="dot ${i===si?"active":""}"></span>`).join("");tnext.textContent=si===slides.length-1?"시작하기":"다음"}function closeT(){tutorial.classList.remove("show");localStorage.setItem("lifeSpecupTutorial","done")}tnext.onclick=()=>{if(si<slides.length-1){si++;drawT()}else closeT()};skip.onclick=closeT;tutorialAgain.onclick=()=>{si=0;drawT();tutorial.classList.add("show")};if(!localStorage.getItem("lifeSpecupTutorial")){drawT();tutorial.classList.add("show")}
const emblemState=JSON.parse(localStorage.getItem("lifeSpecupEmblems")||'{"owned":[],"equipped":[]}');
if(document.querySelector("#headerEmblems")&&window.EMBLEMS){headerEmblems.innerHTML=(emblemState.equipped||[]).slice(0,5).map(id=>{let e=EMBLEMS.find(x=>x.id===id);return e?`<span class="mini-emblem tone-${e.tone}" title="${e.name}">${e.icon}</span>`:""}).join("")}
