const C=LifeSpecupCore,D=CAREER_DATA;let U=C.get("lifeSpecupUser",{}),V=C.get("lifeSpecupVerifiedCerts",[]),sim=new Set();
const roles=Object.keys(D.roles);role.innerHTML=roles.map(x=>`<option>${x}</option>`).join("");if(roles.includes(U.goalJob))role.value=U.goalJob;else if(/데이터센터/.test(U.goalJob||""))role.value="데이터센터 전기시설";else if(/보전|생산/.test(U.goalJob||""))role.value="설비보전 전기직";else role.value="전기 시설관리";
function certSet(extra=sim){let a=new Set((U.certificates||[]).map(x=>x.name));V.filter(x=>x.status==="verified").forEach(x=>a.add(x.name));extra.forEach(x=>a.add(x));return a}
function envAdjust(profile){let p=JSON.parse(JSON.stringify(profile));if(environment.value==="datacenter"){p.skills=[...new Set([...p.skills,"UPS·비상전원"])];p.baseCareer=Math.max(p.baseCareer,2)}if(environment.value==="factory")p.skills=[...new Set([...p.skills,"설비 트러블 대응"])];if(environment.value==="public")p.skills=[...new Set([...p.skills,"법정점검·문서 대응"])];return p}
function compute(extra=sim){let p=envAdjust(D.roles[role.value][roleLevel.value]),certs=certSet(extra),career=(+U.careerYears||0)+(extra.has("career1")?1:0)+(extra.has("career2")?2:0),items=[];
let primaryCert=p.certs.find(x=>certs.has(x)),certOk=!!primaryCert;
items.push({id:"cert",name:"핵심 전기 자격",current:primaryCert||"미충족",target:p.certs.join(" 또는 "),ok:certOk,weight:32,kind:"자격",hard:roleLevel.value!=="entry",evidence:roleLevel.value==="qualified"?"공고·법령 사례":"공고 사례"});
let careerOk=career>=p.baseCareer;items.push({id:"career",name:"관련 실무경력",current:`${career}년`,target:p.baseCareer?`${p.baseCareer}년 이상`:"신입 지원 가능 범위 포함",ok:careerOk,ratio:p.baseCareer?Math.min(1,career/p.baseCareer):1,weight:28,kind:"경력",hard:roleLevel.value!=="entry"&&p.baseCareer>0,evidence:"공고 사례"});
let skillMatch=0,job=(U.currentJob||"")+" "+(U.industry||"");if(/전기|시설|설비|보전/.test(job))skillMatch=.55;if(extra.has("skill"))skillMatch=1;items.push({id:"skill",name:"직무 연관 경험",current:skillMatch>=.5?"관련 업무 입력됨":"구체적 경험 미입력",target:p.skills.slice(0,3).join(" · "),ok:skillMatch>=.8,ratio:skillMatch,weight:22,kind:"경험",hard:false,evidence:"직무 요구 추정"});
let bonus=p.bonusCerts||[],bonusHit=bonus.filter(x=>certs.has(x));items.push({id:"bonus",name:"복수 자격·우대요소",current:bonusHit.length?bonusHit.join(", "):"미보유/미입력",target:bonus.length?bonus.join(" · "):"포지션별 우대",ok:bonusHit.length>0,ratio:bonus.length?Math.min(1,bonusHit.length/bonus.length):.5,weight:10,kind:"우대",hard:false,evidence:"공고 사례"});
let edu=U.education||"미입력",eduRatio=edu==="미입력"?0.35:0.75;items.push({id:"edu",name:"학력·전공 조건",current:edu,target:p.education,ok:eduRatio>=.7,ratio:eduRatio,weight:8,kind:"학력",hard:false,evidence:"공고별 편차"});
let score=Math.round(items.reduce((s,x)=>s+x.weight*(x.ok?1:(x.ratio||0)),0)),hard=items.filter(x=>x.hard),hardPassed=hard.filter(x=>x.ok).length,blockers=hard.filter(x=>!x.ok);return{p,items,score,hardScore:hard.length?Math.round(hardPassed/hard.length*100):100,blockers,career,certs}}
function impactCandidates(base){let opts=[];["전기기사","전기산업기사","소방설비기사(전기분야)"].forEach(x=>{if(!base.certs.has(x)){let e=new Set(sim);e.add(x);let n=compute(e);if(n.score>base.score)opts.push({id:x,label:x,delta:n.score-base.score,type:"cert"})}});["career1","career2","skill"].forEach(id=>{if(!sim.has(id)){let e=new Set(sim);e.add(id),n=compute(e),labels={career1:"관련경력 +1년",career2:"관련경력 +2년",skill:"핵심 실무경험 확보"};if(n.score>base.score)opts.push({id,label:labels[id],delta:n.score-base.score,type:"growth"})}});return opts.sort((a,b)=>b.delta-a.delta)}
function renderAnalysis(){let r=compute(),opts=impactCandidates(r);analysisArea.style.display="block";fitScore.textContent=r.score+"/100";hardScore.textContent=r.hardScore+"%";confidence.textContent=r.p.confidence;evidenceCount.textContent=`근거 ${D.evidence.length}개 + 규칙 추정`;bigGap.textContent=r.blockers[0]?.kind||r.items.filter(x=>!x.ok).sort((a,b)=>b.weight-a.weight)[0]?.kind||"낮음";
blocker.innerHTML=r.blockers.length?`<div class="blocker-box"><b>⚠ 먼저 해결해야 할 조건</b><p>${r.blockers.map(x=>x.name+" · "+x.target).join("<br>")}</p><small>필수조건을 충족하지 못하면 전체 점수와 별개로 일부 포지션 지원이 제한될 수 있습니다.</small></div>`:`<div class="ready-box">✓ 현재 입력정보 기준으로 명확한 필수조건 BLOCKER는 없습니다. 경쟁력 항목을 강화해보세요.</div>`;
requirements.innerHTML=r.items.map(x=>`<div class="req-row"><div class="req-state ${x.ok?"met":x.hard?"blocked":"gap"}">${x.ok?"✓":x.hard?"!":"△"}</div><div class="req-body"><div class="row-head"><b>${x.name}</b><span class="source-tag">${x.evidence}</span></div><div class="req-compare"><span>${x.current}</span><i>→</i><strong>${x.target}</strong></div></div><em>${x.ok?"충족":x.hard?"필수 격차":"강화 가능"}</em></div>`).join("");
roadmap.innerHTML=(opts.slice(0,4).map((x,i)=>`<div class="road-step"><span>${i+1}</span><div><b>${x.label}</b><p>현재 모델에서 시장 적합도 <strong>+${x.delta}</strong> 예상</p></div>${x.type==="cert"?`<button class="secondary smallbtn" onclick="startGoal('${x.id}')">목표로</button>`:""}</div>`).join("")||'<div class="empty">큰 격차가 없습니다. 실제 공고 단위 비교가 다음 단계입니다.</div>');
simOptions.innerHTML=opts.slice(0,6).map(x=>`<button class="sim-chip ${sim.has(x.id)?"on":""}" onclick="toggleSim('${x.id}')">${sim.has(x.id)?"✓ ":""}${x.label} <small>+${x.delta}</small></button>`).join("");let clean=new Set(),before=compute(clean).score;beforeScore.textContent=before;afterScore.textContent=r.score;simDelta.textContent=sim.size?`가상 변화 +${r.score-before}점`:"스펙을 선택해 미래 상태를 비교하세요.";
evidence.innerHTML=D.evidence.map(e=>`<div class="evidence-row"><span>${e.type}</span><div><b>${e.title}</b><p>${e.detail}</p></div><a href="${e.url}" target="_blank" rel="noopener">근거 보기 ↗</a></div>`).join("");profileMini.innerHTML=`<p class="eyebrow">CURRENT PLAYER</p><h3>${U.nickname||"플레이어"}</h3><p>${U.currentJob||U.employment||"현재 직무 미입력"} · 경력 ${+U.careerYears||0}년</p><small>보유/인증 자격 ${certSet(new Set()).size}개</small>`}
function toggleSim(id){sim.has(id)?sim.delete(id):sim.add(id);renderAnalysis()}function startGoal(name){sessionStorage.setItem("lifeSpecupSuggestedCert",name);location.href="quests.html"}resetSim.onclick=()=>{sim.clear();renderAnalysis()};analyze.onclick=()=>{U.goalJob=role.value;C.set("lifeSpecupUser",U);sim.clear();renderAnalysis()};[role,roleLevel,environment].forEach(x=>x.onchange=()=>{if(analysisArea.style.display!=="none"){sim.clear();renderAnalysis()}});renderAnalysis();