let U=LIFE_DATA.loadUser();LIFE_DATA.saveUser(U);
let future={years:0,certs:new Set(),facility:null},saved=JSON.parse(localStorage.getItem("lifeSpecupCareerProfile")||"{}");
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function certSet(){return new Set(LIFE_DATA.certNames(U))}
function profile(extra=future){let edu=/대학교|대학원/.test(U.education||"")?3:/전문대/.test(U.education||"")?2:1,opic={IL:1,IM1:2,IM2:3,IM3:4,IH:5,AL:6};return{certs:new Set([...certSet(),...extra.certs]),years:CAREER_STORE.totalMonths(U)/12+(extra.years||0),facility:extra.facility||saved.largeFacility||"none",edu,major:saved.majorRelated||"unknown",toeic:+saved.toeic||0,ts:+saved.toeicSpeaking||0,opic:opic[saved.opic]||0}}
function org(){return COMPANY_UNIVERSE.find(x=>x.id===osCompany.value)||COMPANY_UNIVERSE[0]}
function tracks(){return JOB_MARKET.get(org())}
function track(){return tracks().find(x=>x.id===osTrack.value)||tracks()[0]}
function renderMarketMap(){
 let p=profile({years:future.years,certs:future.certs,facility:future.facility}),ex=exam(),rows=MARKET_MAP.segments.map(seg=>({seg,r:MARKET_MAP.evaluate(seg,p,ex)}));
 marketLanes.innerHTML=rows.map(({seg,r})=>`<article class="market-lane ${seg.kind}"><div class="lane-head"><i>${seg.icon}</i><div><b>${seg.name}</b><small>${seg.note}</small></div><strong>${r.score}</strong></div><div class="lane-meter"><i style="width:${r.score}%"></i><em style="left:${seg.baseline}%"></em></div><div class="lane-foot"><span>${r.level}</span><small>시장기준 ${seg.baseline}${r.caps.length?" · "+r.caps.join(" · "):""}</small></div></article>`).join("");
 let best=rows.filter(x=>x.seg.kind!=="public_ncs"||(!x.r.caps.length)).sort((a,b)=>b.r.gap-a.r.gap)[0],weak=rows.sort((a,b)=>a.r.gap-b.r.gap)[0];
 marketInsight.innerHTML=`<div><small>현재 상대적으로 유리한 시장</small><b>${best?.seg.name||"데이터 부족"}</b><span>${best?best.r.level:""}</span></div><div><small>추가 준비가 큰 시장</small><b>${weak?.seg.name||"-"}</b><span>${weak?.r.caps[0]||"역량 보강 필요"}</span></div>`;
}
function renderPublicWorkerCases(){publicWorkerCases.innerHTML=MARKET_MAP.publicWorkerEvidence.map(x=>`<article><div><span class="confidence conf-${x.confidence}">근거 확인</span><b>${x.name}</b></div><p>${x.education} · ${x.employment} · ${x.ncsExam?"필기 있음":"NCS 필기 없음"}</p><strong>${x.certRule}</strong><small>${x.process.join(" → ")}</small><a href="${x.sourceUrl}" target="_blank">JOB-ALIO 근거 보기 ↗</a></article>`).join("")}
function populate(){let target=U.targetCompanyId||"co001";osCompany.innerHTML=COMPANY_UNIVERSE.map(x=>`<option value="${x.id}" ${x.id===target?"selected":""}>${x.name}</option>`).join("");syncTracks()}
function syncTracks(){let a=tracks();osTrack.innerHTML=a.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");render()}
function exam(){return{ncs:saved.ncs?+saved.ncs:null,exam:saved.majorExam?+saved.majorExam:null}}
function evaluate(extra=future){return CAREER_SCORE.evaluate(track(),profile(extra),exam())}
function draw(vals,base){let cv=osRadar,ctx=cv.getContext("2d"),cx=cv.width/2,cy=cv.height/2+5,R=100,keys=["자격","경력","실무","학력","직무","어학"],arr=[vals.cert,vals.career,vals.experience,vals.education,vals.fit,vals.language];ctx.clearRect(0,0,cv.width,cv.height);ctx.textAlign="center";ctx.font="12px sans-serif";for(let q=1;q<=4;q++){ctx.beginPath();for(let i=0;i<6;i++){let a=-Math.PI/2+i*Math.PI/3,r=R*q/4,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.strokeStyle="#263b58";ctx.stroke()}function poly(v,stroke,fill){ctx.beginPath();v.forEach((n,i)=>{let a=-Math.PI/2+i*Math.PI/3,r=R*Math.min(100,n||0)/100,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.strokeStyle=stroke;ctx.fillStyle=fill;ctx.fill();ctx.stroke()}poly(Array(6).fill(base),"#66758b","rgba(100,110,130,.06)");poly(arr,"#8ab4ff","rgba(100,150,240,.2)");keys.forEach((k,i)=>{let a=-Math.PI/2+i*Math.PI/3;ctx.fillStyle="#9fb1c9";ctx.fillText(k,cx+Math.cos(a)*(R+30),cy+Math.sin(a)*(R+24)+4)})}
function moveCandidates(p){let t=track(),items=[];[["관련경력 +1년",{years:1}],["관련경력 +2년",{years:2}],["전기기사",{cert:"전기기사"}],["전기산업기사",{cert:"전기산업기사"}],["대형시설 직접운영",{facility:"strong"}],["소방전기",{cert:"소방설비기사(전기분야)"}]].forEach(([name,ch])=>{let m=CAREER_SCORE.marginal(t,p,ch,exam());if(m.delta>0)items.push({name,delta:m.delta})});return items.sort((a,b)=>b.delta-a.delta).slice(0,3)}
function render(){
 let o=org(),t=track(),p=profile({years:0,certs:new Set(),facility:null}),a=CAREER_SCORE.evaluate(t,p,exam()),f=evaluate();
 osEvidence.innerHTML=`<span class="confidence conf-${t.confidence}">신뢰도 ${t.confidence==="high"?"높음":t.confidence==="medium"?"보통":"낮음"}</span><small>${esc(t.evidence)}</small>${t.sourceUrl?`<a class="source-link" href="${t.sourceUrl}" target="_blank">근거 공고 보기 ↗</a>`:""}`;
 osScore.textContent=a.score;osBase.textContent=a.baseline;osGap.textContent=`GAP ${a.gap>=0?"+":""}${a.gap} · ${a.position}`;osRange.textContent=`AI 추정범위 ${a.range[0]}–${a.range[1]} · 데이터 커버리지 ${a.coverage}%`;
 osGate.innerHTML=a.caps.length?`<div class="gate warn">⚠ ${a.caps.map(esc).join(" · ")}</div>`:`<div class="gate good">✓ 확인된 핵심요건상 치명적 미달 없음</div>`;
 draw(a.components,a.baseline);
 osMoves.innerHTML=moveCandidates(p).map((x,i)=>`<div class="move"><b>${i+1}</b><span>${x.name}</span><strong>예상 +${x.delta}</strong></div>`).join("")||'<p class="sub">현재 입력만으로 우선순위를 계산하기 어렵습니다.</p>';
 let labels={cert:"자격",career:"관련경력",experience:"실무환경",education:"학력·전공",fit:"직무적합",language:"어학",ncs:"NCS",exam:"전공필기"};
 osBreakdown.innerHTML=Object.entries(t.axes).map(([k,w])=>`<div class="break-row"><span>${labels[k]}</span><div><i style="width:${a.components[k]??0}%"></i></div><b>${a.components[k]??"미입력"}</b><small>비중 ${w}%</small></div>`).join("")+`<p class="score-note">※ ${t.confidence==="high"?"최근 확인된 채용트랙을 우선 반영":"회사 고유 합격자 데이터가 부족해 동종시장 모델을 사용"}했습니다. 이 수치는 실제 합격확률이 아닙니다.</p>`;
 let cur=CAREER_STORE.current(U),yrs=(CAREER_STORE.totalMonths(U)/12).toFixed(1);osProfile.innerHTML=`<div class="profile-facts"><span>현재직무 <b>${esc(cur?.job||U.currentJob||"미설정")}</b></span><span>관련경력 <b>${yrs}년</b></span><span>자격 <b>${[...certSet()].join(", ")||"없음"}</b></span><span>경력 기준일 <b>${CAREER_STORE.dateKey()}</b></span></div>`;
 let currentYears=CAREER_STORE.totalMonths(U)/12,totalFuture=currentYears+future.years;futureNow.textContent=a.score;futureScore.textContent=f.score;futureDelta.textContent=`${f.score-a.score>=0?"+":""}${f.score-a.score}`;
 currentCareerSpec.textContent=`${currentYears.toFixed(1)}년`;currentCareerDetail.textContent=cur?`${cur.job} · ${cur.startDate||"입사일 미입력"} ~ 현재`:"등록된 현재 경력 없음";
 let owned=[...certSet()];currentCertSpec.innerHTML=owned.length?owned.map(n=>`<span>${esc(n)}</span>`).join(""):'<span class="empty-tag">등록 자격 없음</span>';
 careerProjection.innerHTML=`<span>현재 ${currentYears.toFixed(1)}년</span><i>+</i><span>추가 ${Math.floor(future.years)}년 ${Math.round((future.years%1)*12)}개월</span><i>=</i><b>미래 ${totalFuture.toFixed(1)}년</b>`;
 futureCertSelected.innerHTML=future.certs.size?[...future.certs].map(n=>`<span>${esc(n)} <button data-certremove="${encodeURIComponent(n)}">×</button></span>`).join(""):'<small>추가할 자격증을 검색하세요.</small>';
 futureCompare.innerHTML=`<div><span>관련경력</span><b>${currentYears.toFixed(1)}년 → ${totalFuture.toFixed(1)}년</b></div><div><span>자격증</span><b>${owned.length}개 → ${owned.length+future.certs.size}개</b></div>`;
 futureText.textContent=`${future.years?`관련경력 +${Math.floor(future.years)}년 ${Math.round((future.years%1)*12)}개월`:"추가 경력 없음"}${future.certs.size?" · "+[...future.certs].join(", "):""}${future.facility?" · 대형시설 경험":""}`;
 [...document.querySelectorAll("#expChoices button")].forEach(b=>b.classList.toggle("selected",b.dataset.exp&&future.facility===b.dataset.exp));
 U.targetCompanyId=o.id;LIFE_DATA.saveUser(U);renderMarketMap()
}
osCompany.onchange=syncTracks;osTrack.onchange=render;
function syncFutureCareerFromInputs(){let y=Math.max(0,+futureYearsInput.value||0),m=Math.max(0,Math.min(11,+futureMonthsInput.value||0));futureMonthsInput.value=m;future.years=y+m/12;render()}
futureYearsInput.oninput=syncFutureCareerFromInputs;futureMonthsInput.oninput=syncFutureCareerFromInputs;
document.querySelector(".quick-career").onclick=e=>{let b=e.target.closest("[data-addm]");if(!b)return;let total=Math.round(future.years*12)+(+b.dataset.addm);futureYearsInput.value=Math.floor(total/12);futureMonthsInput.value=total%12;syncFutureCareerFromInputs()};
function certCatalog(){return (window.CERTS||[]).map(x=>x.name).filter(Boolean)}
function renderCertSearch(){let q=futureCertSearch.value.trim().toLowerCase(),owned=certSet();if(!q){futureCertResults.innerHTML="";futureCertResults.classList.remove("open");return}let list=[...new Set(certCatalog())].filter(n=>n.toLowerCase().includes(q)&&!owned.has(n)&&!future.certs.has(n)).slice(0,12);futureCertResults.innerHTML=list.length?list.map(n=>`<button data-certadd="${encodeURIComponent(n)}"><b>${esc(n)}</b><span>미래 스펙에 추가</span></button>`).join(""):`<div class="empty-mini">추가 가능한 자격증이 없습니다.</div>`;futureCertResults.classList.add("open")}
futureCertSearch.oninput=renderCertSearch;futureCertResults.onclick=e=>{let b=e.target.closest("[data-certadd]");if(!b)return;future.certs.add(decodeURIComponent(b.dataset.certadd));futureCertSearch.value="";futureCertResults.classList.remove("open");render()};
futureCertSelected.onclick=e=>{let b=e.target.closest("[data-certremove]");if(!b)return;future.certs.delete(decodeURIComponent(b.dataset.certremove));render()};
expChoices.onclick=e=>{let b=e.target.closest("[data-exp]");if(!b)return;future.facility=future.facility===b.dataset.exp?null:b.dataset.exp;render()};
resetFuture.onclick=()=>{future={years:0,certs:new Set(),facility:null};futureYearsInput.value=0;futureMonthsInput.value=0;futureCertSearch.value="";futureCertResults.innerHTML="";render()};
function listCompanies(q=""){let f=COMPANY_UNIVERSE.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())).slice(0,60);companyList.innerHTML=f.map(x=>`<button data-id="${x.id}"><b>${x.name}</b><span>${x.category}</span><small>신뢰도 ${x.research?.confidence==="high"?"높음":x.research?.confidence==="medium"?"보통":"낮음"}</small></button>`).join("")}
renderPublicWorkerCases();companySearch.oninput=()=>listCompanies(companySearch.value);companyList.onclick=e=>{let b=e.target.closest("[data-id]");if(!b)return;osCompany.value=b.dataset.id;syncTracks();scrollTo({top:0,behavior:"smooth"})};listCompanies();populate();