const C=LifeSpecupCore,D=COMPANY_CAREER_DATA;let U=C.get("lifeSpecupUser",{}),V=C.get("lifeSpecupVerifiedCerts",[]),P=C.get("lifeSpecupCareerPrefs",{}),sim=new Set();
const EDU={unknown:0,high:1,college:2,university:3,graduate:4},OPIC={"":0,IL:1,IM1:2,IM2:3,IM3:4,IH:5,AL:6};
function certs(extra=sim){let a=new Set((U.certificates||[]).map(x=>x.name));V.filter(x=>x.status==="verified").forEach(x=>a.add(x.name));extra.forEach(x=>{if(!x.startsWith("_"))a.add(x)});return a}
function company(){return D.companies[targetCompany.value]||D.companies.s1}
function fillTracks(){let c=company(),old=companyTrack.value;companyTrack.innerHTML=Object.entries(c.tracks).map(([id,t])=>`<option value="${id}">${t.label}</option>`).join("");if([...companyTrack.options].some(o=>o.value===old))companyTrack.value=old;else if(P.companyTrack&&[...companyTrack.options].some(o=>o.value===P.companyTrack))companyTrack.value=P.companyTrack}
function profile(extra=sim){return{age:+age.value||0,years:(+relatedYears.value||0)+(extra.has("_y1")?1:0),toeic:+toeic.value||0,ts:extra.has("_lang")?Math.max(110,+toeicSpeaking.value||0):(+toeicSpeaking.value||0),opic:extra.has("_lang")?Math.max(1,OPIC[opic.value]||0):(OPIC[opic.value]||0),edu:extra.has("_edu")?Math.max(2,EDU[educationLevel.value]||0):(EDU[educationLevel.value]||0),major:majorRelated.value,facility:extra.has("_facility")?"strong":largeFacility.value,certs:certs(extra)}}
function track(){return company().tracks[companyTrack.value]||Object.values(company().tracks)[0]}
function companyCalc(extra=sim){let t=track(),p=profile(extra),items=[],eduNeed=EDU[t.educationMin]||0,eduOK=p.edu>=eduNeed,majorOK=p.major==="yes",langOK=!t.language||(p.ts>=t.language.toeicSpeaking||p.opic>=OPIC[t.language.opic]),careerOK=p.years>=t.careerMin,certHit=t.certs.filter(x=>p.certs.has(x));
items.push({id:"edu",name:"최종학력",hard:true,ok:eduOK,current:Object.keys(EDU).find(k=>EDU[k]===p.edu)||"미입력",target:t.educationMin==="college"?"2·3년제 이상":"공고 기준",weight:20,source:"공고"});
items.push({id:"major",name:"관련 전공",hard:true,ok:majorOK,current:p.major==="yes"?"관련 전공":"비관련/미입력",target:t.major.join(" · ")+" 관련 학과",weight:24,source:"공고"});
if(t.language)items.push({id:"language",name:"공인 영어회화",hard:true,ok:langOK,current:p.ts?`TOEIC Speaking ${p.ts}`:p.opic?`OPIc ${Object.keys(OPIC).find(k=>OPIC[k]===p.opic)}`:"미보유",target:`OPIc ${t.language.opic} 또는 TOEIC Speaking ${t.language.toeicSpeaking}+`,weight:18,source:"공고"});
items.push({id:"career",name:"관련경력",hard:t.careerMin>0,ok:careerOK,current:`${p.years}년`,target:t.careerMin?`${t.careerMin}년+`:`${t.hire} · 경력 필수 아님`,weight:t.careerMin?22:6,source:"공고"});
items.push({id:"cert",name:"관련 자격증",hard:t.certMode==="required",ok:certHit.length>0,current:certHit.join(" · ")||"미보유",target:t.certs.length?t.certs.join(" · "):"직무 관련 자격",weight:t.certMode==="preferred"?18:22,source:t.certMode==="preferred"?"우대":"경쟁력"});
items.push({id:"experience",name:"직무 경험의 질",hard:false,ok:p.facility==="strong",ratio:p.facility==="strong"?1:p.facility==="some"?.55:.15,current:p.facility==="strong"?"대형시설 직접운영":p.facility==="some"?"보조·일부 경험":"구체적 경험 미입력",target:t.tasks.join(" · "),weight:14,source:"직무내용"});
let hard=items.filter(i=>i.hard),eligible=hard.length?Math.round(hard.filter(i=>i.ok).length/hard.length*100):100;
let competitiveItems=items.filter(i=>!i.hard||i.id==="cert"||i.id==="experience"),raw=competitiveItems.reduce((s,i)=>s+i.weight*(i.ok?1:(i.ratio||0)),0),den=competitiveItems.reduce((s,i)=>s+i.weight,0),comp=den?Math.round(raw/den*70):35;
if(eligible===100)comp+=15;else comp-=Math.round((100-eligible)*.18);if(certHit.length)comp+=8;if(p.facility==="strong")comp+=5;comp=Math.max(5,Math.min(92,comp));
let trajectory=75;if(p.age&&p.age>=35&&p.years===0)trajectory=t.hire==="신입"?58:32;else if(p.years>=2)trajectory=82;
return{mode:"company",t,p,items,eligible,comp,trajectory,blockers:hard.filter(i=>!i.ok),certHit}}
function marketCalc(extra=sim){let p=profile(extra),core=["전기기사","전기산업기사"],hit=core.find(x=>p.certs.has(x)),need=companyTier.value==="large"?2:companyTier.value==="mid"?1:0,careerOK=p.years>=need,items=[{id:"cert",name:"핵심 전기자격",hard:companyTier.value!=="small",ok:!!hit,current:hit||"미보유",target:core.join(" 또는 "),weight:30,source:"시장모델"},{id:"career",name:"관련경력",hard:need>0,ok:careerOK,ratio:need?Math.min(1,p.years/need):1,current:`${p.years}년`,target:need?`${need}년+`:"경력무관 범위",weight:34,source:"시장모델"},{id:"experience",name:"현장경험",hard:false,ok:p.facility==="strong",ratio:p.facility==="strong"?1:p.facility==="some"?.55:.15,current:p.facility,target:"직접 운영 경험",weight:20,source:"추정"}],hard=items.filter(i=>i.hard),eligible=hard.length?Math.round(hard.filter(i=>i.ok).length/hard.length*100):100,raw=items.reduce((s,i)=>s+i.weight*(i.ok?1:(i.ratio||0)),0),den=items.reduce((s,i)=>s+i.weight,0),comp=Math.round(raw/den*80)-(companyTier.value==="large"?10:0);if(eligible<100)comp-=15;comp=Math.max(5,Math.min(90,comp));return{mode:"market",t:{label:"시장 평균 · "+role.value,confidence:"보통",year:"2024~2026"},p,items,eligible,comp,trajectory:p.years>=2?80:60,blockers:hard.filter(i=>!i.ok),certHit:hit?[hit]:[]}}
function calc(extra=sim){return analysisMode.value==="company"?companyCalc(extra):marketCalc(extra)}
function candidates(base){let ids=analysisMode.value==="company"?[...(base.t.certs||[]),"_facility","_lang","_edu","_y1"]:["전기기사","전기산업기사","_facility","_y1"],labels={_facility:"핵심 현장경험 확보",_lang:"공인 영어회화 기준 충족",_edu:"학력조건 충족",_y1:"관련경력 +1년"};return ids.filter(id=>!sim.has(id)&&!base.p.certs.has(id)).map(id=>{let e=new Set(sim);e.add(id),n=calc(e);return{id,label:labels[id]||id,delta:n.comp-base.comp,elig:n.eligible-base.eligible}}).filter(x=>x.delta>0||x.elig>0).sort((a,b)=>(b.elig-a.elig)||(b.delta-a.delta))}
function render(){let r=calc(),opts=candidates(r);analysisArea.style.display="block";eligibility.textContent=r.eligible+"%";fitScore.textContent=r.comp+"/100";trajectory.textContent=r.trajectory+"/100";confidence.textContent=r.t.confidence||"보통";evidenceCount.textContent=analysisMode.value==="company"?`최근 트랙 공고 ${r.t.year} · ${r.t.sources?.length||0}개 근거`:"2024~2026 시장 모델";
freshness.innerHTML=analysisMode.value==="company"?`<div class="freshness-card"><div><span>LIVE PROFILE</span><b>${company().name} · ${r.t.label}</b></div><div><small>근거기간</small><strong>2024~2026</strong></div><div><small>최근 트랙 데이터</small><strong>${r.t.year}</strong></div><div><small>신뢰도</small><strong>${r.t.confidence}</strong></div></div>`:`<div class="notice">특정 회사가 아닌 시장 평균 추정 모드입니다. 회사·채용트랙 모드보다 정확도가 낮습니다.</div>`;
verdict.innerHTML=`<div class="career-verdict"><div><p class="eyebrow">${analysisMode.value==="company"?"COMPANY TRACK":"MARKET MODEL"}</p><h2>${r.t.label}</h2><p>${r.eligible<100?"현재 확인된 지원조건 중 미충족 항목이 있습니다. 우대 스펙보다 먼저 지원자격을 확인해야 합니다.":r.comp>=65?"지원조건을 충족하고 경쟁력 요소도 비교적 잘 갖춘 상태입니다.":"지원조건과 실제 경쟁력은 다릅니다. 아래 우대·직무경험을 강화할 여지가 있습니다."} ${r.p.age>=35&&r.p.years===0?"나이는 직접 감점하지 않았으며, 관련경력 0년이라는 경력 궤적만 별도 해석합니다.":""}</p></div><div class="verdict-number"><small>COMPETITIVENESS</small><b>${r.comp}</b></div></div>`;
blocker.innerHTML=r.blockers.length?`<div class="blocker-box"><b>지원조건 확인 필요</b><p>${r.blockers.map(x=>`${x.name}: ${x.current} → ${x.target}`).join("<br>")}</p><small>공고에 명시된 조건은 자격증 가산점으로 상쇄하지 않습니다.</small></div>`:`<div class="ready-box">✓ 입력정보 기준으로 확인된 지원조건은 충족합니다. 이제 우대조건과 실제 직무경험을 비교합니다.</div>`;
requirements.innerHTML=r.items.map(i=>`<div class="req-row"><div class="req-state ${i.ok?"met":i.hard?"blocked":"gap"}">${i.ok?"✓":i.hard?"!":"△"}</div><div class="req-body"><div class="row-head"><b>${i.name}</b><span class="source-tag">${i.source}</span></div><div class="req-compare"><span>${i.current}</span><i>→</i><strong>${i.target}</strong></div></div><em>${i.hard?"지원조건":i.ok?"강점":"경쟁력"}</em></div>`).join("");
roadmap.innerHTML=opts.slice(0,5).map((o,i)=>`<div class="road-step"><span>${i+1}</span><div><b>${o.label}</b><p>${o.elig?`지원조건 +${o.elig}% · `:""}경쟁력 변화 +${o.delta}</p></div>${!o.id.startsWith("_")?`<button class="secondary smallbtn" onclick="startGoal('${o.id}')">목표로</button>`:""}</div>`).join("")||'<div class="empty">현재 모델에서 큰 단일 격차가 없습니다.</div>';
simOptions.innerHTML=opts.slice(0,7).map(o=>`<button class="sim-chip" onclick="toggleSim('${o.id}')">${o.label} <small>${o.delta>=0?"+":""}${o.delta}</small></button>`).join("");let clean=calc(new Set());beforeScore.textContent=clean.comp;afterScore.textContent=r.comp;simDelta.textContent=sim.size?`가상 변화 ${r.comp-clean.comp>=0?"+":""}${r.comp-clean.comp}점`:"스펙을 선택해 미래 상태를 비교하세요.";
let srcs=analysisMode.value==="company"?(r.t.sources||[]).map(id=>D.sources[id]).filter(Boolean):Object.values(D.sources);evidence.innerHTML=srcs.map(e=>`<div class="evidence-row"><span>${e.date}</span><div><b>${e.title}</b><p>${e.detail}</p></div><a href="${e.url}" target="_blank" rel="noopener">원문 ↗</a></div>`).join("");profileMini.innerHTML=`<p class="eyebrow">ANALYSIS TARGET</p><h3>${analysisMode.value==="company"?company().name:"시장 평균"}</h3><p>${r.t.label}</p><small>합격확률이 아닌 요구조건/경쟁력 분석</small>`}
function persist(){P={...P,analysisMode:analysisMode.value,targetCompany:targetCompany.value,companyTrack:companyTrack.value,companyTier:companyTier.value,age:+age.value||0,relatedYears:+relatedYears.value||0,toeic:+toeic.value||0,toeicSpeaking:+toeicSpeaking.value||0,opic:opic.value,educationLevel:educationLevel.value,majorRelated:majorRelated.value,largeFacility:largeFacility.value};C.set("lifeSpecupCareerPrefs",P)}
function toggleSim(id){sim.has(id)?sim.delete(id):sim.add(id);render()}function startGoal(n){sessionStorage.setItem("lifeSpecupSuggestedCert",n);location.href="quests.html"}
function modeUI(){document.querySelectorAll(".company-only").forEach(x=>x.style.display=analysisMode.value==="company"?"":"none");document.querySelectorAll(".market-only").forEach(x=>x.style.display=analysisMode.value==="market"?"":"none");render()}
role.innerHTML=D.marketFallback.roles.map(x=>`<option>${x}</option>`).join("");fillTracks();analysisMode.value=P.analysisMode||"company";age.value=P.age||"";relatedYears.value=P.relatedYears??U.careerYears??0;toeic.value=P.toeic||0;toeicSpeaking.value=P.toeicSpeaking||0;opic.value=P.opic||"";educationLevel.value=P.educationLevel||"unknown";majorRelated.value=P.majorRelated||"unknown";largeFacility.value=P.largeFacility||"none";companyTier.value=P.companyTier||"large";
analysisMode.onchange=modeUI;targetCompany.onchange=()=>{fillTracks();render()};companyTrack.onchange=()=>{sim.clear();render()};companyTier.onchange=render;role.onchange=render;analyze.onclick=()=>{persist();sim.clear();render()};saveProfile.onclick=()=>{persist();C.toast("경쟁력 정보를 저장했습니다.");render()};resetSim.onclick=()=>{sim.clear();render()};modeUI();