const C=LifeSpecupCore,U=C.get("lifeSpecupUser",{}),S=C.get("lifeSpecupState",{xp:0,history:[]}),Q=C.get("lifeSpecupQuests",{selected:[],days:{},long:[]}),F=C.get("lifeSpecupFinance",{}),V=C.get("lifeSpecupVerifiedCerts",[]);
const fmt=n=>Math.round(+n||0).toLocaleString("ko-KR")+"원",today=C.lifeDay(),D=Q.days?.[today]||{quests:Q.selected||[],completed:[]},actions=D.quests||Q.selected||[],done=D.completed||[];
helloName.textContent=U.nickname||"플레이어";lifeDate.textContent=`Life Day ${today} · 오전 6시에 하루가 바뀝니다.`;
let active=(Q.long||[]).find(x=>!x.done&&x.cert);
if(active){let pct=Math.min(100,Math.round((active.loggedHours||0)/(active.targetHours||1)*100));focusCard.innerHTML=`<div><p class="eyebrow">PRIMARY OBJECTIVE</p><h2>${active.cert} ${active.stage==="written"?"필기":"실기"}</h2><p>${active.loggedHours||0} / ${active.targetHours}시간 · ${pct}% 진행</p></div><div class="focus-progress"><div class="progress"><span style="width:${pct}%"></span></div><button class="primary" onclick="location.href='quests.html'">오늘 공부 기록하기</button></div>`}
else focusCard.innerHTML=`<div><p class="eyebrow">PRIMARY OBJECTIVE</p><h2>핵심 목표가 비어 있습니다.</h2><p>자격증·커리어 목표 하나를 정하면 오늘 할 일을 연결해드립니다.</p></div><button class="primary" onclick="location.href='quests.html'">목표 만들기</button>`;
todayRate.textContent=`${done.length}/${actions.length} 완료`;todayActions.innerHTML=actions.length?actions.slice(0,6).map(q=>`<div class="action-line ${done.includes(q.id)?"done":""}"><span>${done.includes(q.id)?"✓":"○"}</span><div><b>${q.name}</b><small>${q.auto?"장기 목표에서 자동 생성":"직접 선택"}</small></div><em>+${q.xp||0} XP</em></div>`).join(""):`<div class="empty-state"><b>오늘 계획이 없습니다.</b><p>3개 정도만 골라 시작하는 것을 권장합니다.</p><button class="secondary" onclick="location.href='quests.html'">계획 만들기</button></div>`;
if(active){let score=active.mockScore??null,rounds=active.rounds||0;goalProgress.innerHTML=`<div class="goal-title"><b>${active.name}</b><span>${active.loggedHours||0}/${active.targetHours}h</span></div><div class="progress"><span style="width:${Math.min(100,(active.loggedHours||0)/(active.targetHours||1)*100)}%"></span></div><div class="goal-signals"><span>기출/모의 ${score===null?"미입력":score+"점"}</span><span>회독 ${rounds}회</span><span>학습일 ${active.studyDays||0}일</span></div>`}else goalProgress.innerHTML='<div class="empty">진행 중인 장기 목표가 없습니다.</div>';
currentPath.textContent=[U.currentJob||U.employment,U.currentCompanyType,U.education,U.careerYears?U.careerYears+"년":""].filter(Boolean).join(" · ")||"현재 상태 미설정";targetPath.textContent=[U.goalJob,U.companyType,U.track,U.hireType].filter(Boolean).join(" · ")||"목표 미설정";
let verified=new Set(V.filter(x=>x.status==="verified").map(x=>x.name)),rec=/전기|시설|설비/.test(U.goalJob||"")?["전기기사","전기산업기사","소방설비기사(전기분야)"]:[];let missing=rec.filter(x=>!verified.has(x));gapHint.innerHTML=missing.length?`<b>현재 확인되는 핵심 격차</b><br>${missing.slice(0,2).join(" · ")} 등 목표 직무와 연결되는 자격 성취가 아직 남아 있습니다. <span class="muted">이 안내는 현재 MVP 규칙 기반이며 채용 합격을 보장하지 않습니다.</span>`:`<b>프로필과 목표를 더 구체화하세요.</b><br>목표가 구체적일수록 다음 행동 추천도 정교해집니다.`;
let li=C.levelInfo(S.xp||0);level.textContent=li.level;levelBar.style.width=li.pct+"%";levelXp.textContent=`${li.cur}/${li.need} XP`;certCount.textContent=V.filter(x=>x.status==="verified").length+"개";
let assets=(F.deposits||[]).reduce((s,x)=>s+(+x.amount||0),0)+(F.stocks||[]).reduce((s,x)=>s+(+x.amount||0),0)+(F.housing||[]).reduce((s,x)=>s+(+x.assetValue||0)+(+x.deposit||0),0),debt=(F.debts||[]).reduce((s,x)=>s+(+x.balance||0),0),save=(F.deposits||[]).reduce((s,x)=>s+(+x.monthlySaving||0),0)+(F.stocks||[]).reduce((s,x)=>s+(+x.monthlyInvest||0),0);netWorth.textContent=fmt(assets-debt);monthlyFlow.textContent="월 저축·투자 "+fmt(save);
let keys=Object.keys(Q.days||{}).sort().reverse().slice(0,7),tot=0,ok=0;keys.forEach(k=>{let d=Q.days[k],n=(d.quests||[]).length;tot+=n;ok+=(d.completed||[]).length});weekRate.textContent=(tot?Math.round(ok/tot*100):0)+"%";
recentHistory.innerHTML=(S.history||[]).slice(0,6).map(h=>`<div class="history-row"><span>${h.text}</span><b>${h.xp?`+${h.xp} XP`:""}</b></div>`).join("")||'<div class="empty">아직 성장 기록이 없습니다.</div>';