let user=JSON.parse(localStorage.getItem("lifeSpecupUser")||"{}");
let verified=JSON.parse(localStorage.getItem("lifeSpecupVerifiedCerts")||"[]"),state=JSON.parse(localStorage.getItem("lifeSpecupState")||'{"xp":0,"history":[]}'),emState=JSON.parse(localStorage.getItem("lifeSpecupEmblems")||'{"owned":[],"equipped":[]}');
state.history=state.history||[];emState.owned=emState.owned||[];emState.equipped=emState.equipped||[];
const xpMap=Object.fromEntries(CERTS.map(c=>[c.name,c.xp])), emblemMap={'전기기능사':'cert-electric-craftsman','전기산업기사':'cert-electric-industrial','전기기사':'cert-electric-engineer'};
function save(){localStorage.setItem("lifeSpecupVerifiedCerts",JSON.stringify(verified));localStorage.setItem("lifeSpecupState",JSON.stringify(state));localStorage.setItem("lifeSpecupEmblems",JSON.stringify(emState));render()}
function toast(m){let e=document.querySelector("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function render(){
 avatar.textContent=(user.nickname||"U")[0];nick.textContent=user.nickname||"플레이어";currentStatus.innerHTML=`<div class="status"><div><dt>현재 직무</dt><dd>${user.currentJob||user.employment||"미설정"}</dd></div><div><dt>회사 유형</dt><dd>${user.currentCompanyType||"미설정"}</dd></div><div><dt>학력</dt><dd>${user.education||"미설정"}</dd></div><div><dt>총 경력</dt><dd>${user.careerYears?user.careerYears+"년":"미설정"}</dd></div></div>`;targetStatus.innerHTML=`<div class="status"><div><dt>목표 직무</dt><dd>${user.goalJob||"미설정"}</dd></div><div><dt>목표 기업</dt><dd>${user.companyType||"미설정"}</dd></div><div><dt>채용 학력요건</dt><dd>${user.track||"미설정"}</dd></div><div><dt>채용 유형</dt><dd>${user.hireType||"미설정"}</dd></div></div>`;
 equipped.innerHTML=emState.equipped.map(id=>{let e=EMBLEMS.find(x=>x.id===id);return e?`<span class="mini-emblem tone-${e.tone}" title="${e.name}">${e.icon}</span>`:""}).join("");
 let claimed=(user.certificates||[]).map(c=>c.name), names=[...new Set([...claimed,...verified.map(v=>v.name)])];myCerts.innerHTML=names.length?names.map(n=>{let v=verified.find(x=>x.name===n),status=v?.status||"unverified";return `<div class="row-card"><div class="row-head"><div><b>${n}</b><div class="muted">${status==="verified"?"✓ 인증 완료 · XP 지급 완료":status==="pending"?"⏳ 증빙 검증 대기":"보유 입력 · 증빙 미인증"}</div></div><span class="${status==="verified"?"good":status==="pending"?"warn":"muted"}">${status==="verified"?"VERIFIED":status==="pending"?"PENDING":"UNVERIFIED"}</span></div></div>`}).join(""):'<p class="sub">등록한 자격증이 아직 없습니다.</p>';
 let pending=verified.filter(v=>v.status==="pending");devVerify.innerHTML=pending.length?`<div class="notice" style="margin-top:14px"><b>MVP 개발용</b><br>실제 AI 검증 서버 연결 전이므로 아래 버튼은 흐름 테스트용입니다.</div>`+pending.map(v=>`<button class="secondary" style="margin-top:8px" onclick="approve('${v.name}')">${v.name} 테스트 승인</button>`).join(" "):"";
}
request.onclick=()=>{let name=certSelect.value,file=proof.files[0];if(!file){toast("증빙 파일을 선택해주세요.");return}let old=verified.find(v=>v.name===name);if(old&&old.status==="verified"){toast("이미 인증된 자격증입니다.");return}if(old){old.status="pending";old.fileName=file.name}else verified.push({name,status:"pending",fileName:file.name,requestedAt:new Date().toISOString()});save();toast("인증 요청을 저장했습니다.")};
function approve(name){let v=verified.find(x=>x.name===name);if(!v||v.status==="verified")return;v.status="verified";v.verifiedAt=new Date().toISOString();let xp=xpMap[name]||0;state.xp=(state.xp||0)+xp;state.history.unshift({date:new Date().toISOString().slice(0,10),text:`🏆 ${name} 취득 인증`,xp});let eid=emblemMap[name];if(eid&&!emState.owned.includes(eid))emState.owned.push(eid);save();toast(`${name} 인증 완료 · +${xp} XP · 엠블렘 획득!`)}
render();
if(window.CERTS&&document.querySelector('#certSelect'))certSelect.innerHTML=CERTS.map(c=>`<option>${c.name}</option>`).join('');

editCurrent.onclick=()=>{currentEditor.innerHTML=`<div class="form-grid" style="margin-top:12px"><label class="field"><span>현재 직무</span><input id="ecJob" value="${user.currentJob||''}"></label><label class="field"><span>현재 회사유형</span><input id="ecCompany" value="${user.currentCompanyType||''}"></label><label class="field"><span>총 경력(년)</span><input id="ecYears" type="number" min="0" step="0.1" value="${user.careerYears||0}"></label></div><button class="primary smallbtn" id="saveCurrent">저장</button>`;saveCurrent.onclick=()=>{user.currentJob=ecJob.value;user.currentCompanyType=ecCompany.value;user.careerYears=+ecYears.value||0;localStorage.setItem('lifeSpecupUser',JSON.stringify(user));currentEditor.innerHTML='';render();toast('현재 상황을 저장했습니다.')}};