const C=LifeSpecupCore,today=C.lifeDay();
let Q=C.get("lifeSpecupQuests",{days:{},long:[],optionalSelected:[]}),S=C.get("lifeSpecupState",{xp:0,history:[]});
Q.days=Q.days||{};Q.long=Q.long||[];Q.optionalSelected=Q.optionalSelected||[];S.history=S.history||[];
const CORE=[
{id:"study",icon:"📚",name:"성장 공부",target:"2시간 이상",xp:2,unit:"시간"},
{id:"spend",icon:"💳",name:"생활비 절제",target:"변동지출 20,000원 이하",xp:2,unit:"원"},
{id:"exercise",icon:"🏃",name:"몸 관리",target:"운동 30분 이상",xp:2,unit:"분"},
{id:"sleep",icon:"🌙",name:"회복",target:"수면 7시간 이상",xp:2,unit:"시간"}];
const OPTIONAL=[
{id:"read",name:"독서 30분",xp:1},{id:"clean",name:"정리정돈 20분",xp:1},{id:"resume",name:"이력서·자소서 30분",xp:1},{id:"job",name:"채용공고 3개 분석",xp:1},{id:"finance",name:"재정 점검 15분",xp:1},{id:"walk",name:"8,000보 걷기",xp:1},{id:"plan",name:"내일 계획 10분",xp:1},{id:"digital",name:"취침 전 디지털 휴식 30분",xp:1}];
const certs=(window.CERTS||[]).map(c=>({...c,level:/기능장/.test(c.name)?"기능장":/기술사/.test(c.name)?"기술사":/산업기사/.test(c.name)?"산업기사":/기능사/.test(c.name)?"기능사":"기사"}));
function save(){C.set("lifeSpecupQuests",Q);C.set("lifeSpecupState",S);render()}
function activeGoal(){return Q.long.find(x=>!x.done&&x.cert&&!x.paused)||Q.long.find(x=>!x.done&&x.cert)}
function primaryFor(day){let g=activeGoal();return g?{id:"primary",icon:"🎯",name:`${g.cert} ${g.stage==="written"?"필기":"실기"}`,target:`${g.dailyHours||2}시간 공부`,xp:2,unit:"시간",goalId:g.id,required:+g.dailyHours||2}:{id:"primary",icon:"🎯",name:"오늘의 핵심 목표",target:"집중 행동 1개 완료",xp:2,unit:"완료"}}
function dayObj(k){if(!Q.days[k])Q.days[k]={coreSnapshot:[...CORE,primaryFor(k)],optional:[],settled:false,result:null};if(!Q.days[k].coreSnapshot)Q.days[k].coreSnapshot=[...CORE,primaryFor(k)];return Q.days[k]}
dayObj(today);
function previousDay(k){let [y,m,d]=k.split("-").map(Number),x=new Date(y,m-1,d);x.setDate(x.getDate()-1);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`}
function pendingDay(){let p=previousDay(today),d=Q.days[p];return d&&!d.settled?p:null}
function conditions(v,core){return core.map(q=>{let ok=false,val="";if(q.id==="study"){ok=v.study>=2;val=`${v.study}시간`}if(q.id==="spend"){ok=v.spend<=20000;val=`${Math.round(v.spend).toLocaleString()}원`}if(q.id==="exercise"){ok=v.exercise>=30;val=`${v.exercise}분`}if(q.id==="sleep"){ok=v.sleep>=7;val=`${v.sleep}시간`}if(q.id==="primary"){ok=q.required?v.primary>=q.required:!!v.primary;val=q.required?`${v.primary}시간`:(v.primary?"완료":"미완료")}return{...q,ok,val}})}
function openSettlement(k){let d=dayObj(k),core=d.coreSnapshot||[...CORE,primaryFor(k)];settleTitle.textContent=`${k} 하루 정산`;settleForm.innerHTML=`<div class="settle-input-grid"><label class="field"><span>📚 총 공부시간</span><input id="sStudy" type="number" min="0" max="24" step=".5" value="0"></label><label class="field"><span>💳 생활 변동지출</span><input id="sSpend" type="number" min="0" step="100" value="0"></label><label class="field"><span>🏃 운동시간(분)</span><input id="sExercise" type="number" min="0" max="600" step="5" value="0"></label><label class="field"><span>🌙 실제 수면시간</span><input id="sSleep" type="number" min="0" max="24" step=".5" value="0"></label><label class="field full"><span>🎯 ${core[4].name} 수행량</span>${core[4].required?`<input id="sPrimary" type="number" min="0" max="24" step=".5" value="0"><small>목표 ${core[4].required}시간</small>`:`<select id="sPrimary"><option value="0">미완료</option><option value="1">완료</option></select>`}</label></div><div class="notice">생활비 절제는 월세·대출·보험료 같은 고정비가 아니라 식비·쇼핑·여가 등 <b>그날의 변동지출</b> 기준입니다.</div>`;
 let els=[sStudy,sSpend,sExercise,sSleep,sPrimary];function preview(){let v={study:+sStudy.value||0,spend:+sSpend.value||0,exercise:+sExercise.value||0,sleep:+sSleep.value||0,primary:+sPrimary.value||0},r=conditions(v,core);settlePreview.innerHTML=`<div class="settle-result">${r.map(x=>`<div class="${x.ok?"pass":"fail"}"><span>${x.ok?"✓":"×"}</span><div><b>${x.name}</b><small>${x.val} / ${x.target}</small></div></div>`).join("")}</div><p class="settle-score">${r.filter(x=>x.ok).length}/5 예상 달성</p>`}els.forEach(x=>x.oninput=preview);preview();confirmSettlement.onclick=()=>confirm(k,core);settleModal.style.display="grid"}
function confirm(k,core){let d=dayObj(k);if(d.settled)return;let v={study:+sStudy.value||0,spend:+sSpend.value||0,exercise:+sExercise.value||0,sleep:+sSleep.value||0,primary:+sPrimary.value||0},r=conditions(v,core),count=r.filter(x=>x.ok).length,base=r.filter(x=>x.ok).reduce((s,x)=>s+x.xp,0),perfect=count===5?3:0,total=base+perfect;d.settled=true;d.result={inputs:v,items:r,count,total,perfect,settledAt:new Date().toISOString()};S.xp=(S.xp||0)+total;S.history.unshift({date:k,text:`📋 하루 정산 ${count}/5${perfect?" · PERFECT DAY":""}`,xp:total});
 let g=activeGoal();if(g&&core[4]?.goalId===g.id&&v.primary>0){g.loggedHours=Math.min(g.targetHours,(g.loggedHours||0)+v.primary);g.studyDays=(g.studyDays||0)+1;g.lastStudyDay=k}
 updateStreakAchievements();settleModal.style.display="none";save();C.toast(`${count}/5 정산 완료 · +${total} XP`)}
function updateStreakAchievements(){let keys=Object.keys(Q.days).filter(k=>Q.days[k].settled).sort().reverse(),streak=0;for(let k of keys){if((Q.days[k].result?.count||0)>=4)streak++;else break}S.achievements=S.achievements||[];[[7,10,"7일 루틴"],[30,40,"30일 루틴"]].forEach(([n,xp,name])=>{let id="routine-"+n;if(streak>=n&&!S.achievements.includes(id)){S.achievements.push(id);S.xp=(S.xp||0)+xp;S.history.unshift({date:today,text:`🔥 ${name} 달성`,xp})}})}
function toggleOptional(id){let d=dayObj(today);d.optional=d.optional||[];if(d.optional.includes(id))d.optional=d.optional.filter(x=>x!==id);else if(d.optional.length<3)d.optional.push(id);else return C.toast("선택 퀘스트는 하루 최대 3개입니다.");save()}
function completeOptional(id){let d=dayObj(today);d.optionalDone=d.optionalDone||[];if(d.optionalDone.includes(id))return;let q=OPTIONAL.find(x=>x.id===id);d.optionalDone.push(id);S.xp=(S.xp||0)+q.xp;S.history.unshift({date:today,text:"＋ "+q.name,xp:q.xp});save()}
function studyModel(c,stage){let base={기능사:[35,60],산업기사:[70,120],기사:[100,170],기능장:[180,300],기술사:[450,750]}[c.level]||[80,140];if(stage==="practical")base=base.map(x=>Math.round(x*1.15));if(c.name==="전기기사")base=stage==="written"?[120,180]:[140,220];return{low:base[0],high:base[1]}}
function previewGoal(){let c=certs.find(x=>x.name===certName.value)||{name:"전기기사",level:"기사"},stage=certStage.value,h=+dailyHours.value,days=+planDays.value,total=h*days,m=studyModel(c,stage);goalPreview.innerHTML=`<div class="goal-plan-preview"><div><small>계획 학습량</small><b>${total}시간</b></div><div><small>참고 학습범위</small><b>${m.low}~${m.high}시간</b></div><div><small>기간</small><b>${days}일</b></div></div><div class="notice">학습시간 범위는 공식 합격 기준이 아니라 MVP 참고치입니다. 실제 준비도는 시간 외에 기출점수·회독·학습일수를 함께 반영합니다.</div>`}
function createLong(){let c=certs.find(x=>x.name===certName.value),stage=certStage.value,h=+dailyHours.value,days=+planDays.value,total=h*days;if(!c)return;Q.long.filter(x=>!x.done).forEach(x=>x.paused=true);Q.long.push({id:"goal-"+Date.now(),name:`${c.name} ${stage==="written"?"필기":"실기"}`,cert:c.name,stage,dailyHours:h,days,targetHours:total,loggedHours:0,studyDays:0,mockScore:null,rounds:0,started:today,done:false,paused:false,xp:Math.max(20,Math.round(total/6))});Q.days[today].coreSnapshot=[...CORE,primaryFor(today)];goalBuilder.style.display="none";save();C.toast("핵심 장기목표를 시작했습니다.")}
function render(){
 dayChip.textContent=`Life Day · ${today}`;
 let d=dayObj(today),core=d.coreSnapshot||[...CORE,primaryFor(today)];
 coreFive.innerHTML=core.map((q,i)=>`<div class="core-card"><div class="core-number">0${i+1}</div><div class="core-icon">${q.icon}</div><b>${q.name}</b><p>${q.target}</p><small>다음날 자동 판정 · +${q.xp} XP</small></div>`).join("");
 let g=activeGoal();document.querySelector("#activeGoal").innerHTML=g?`<div class="active-goal-card"><div><span class="badge">${g.stage==="written"?"필기":"실기"}</span><h3>${g.cert}</h3><p>${g.loggedHours||0}/${g.targetHours}시간 · 학습일 ${g.studyDays||0}일</p></div><div class="progress"><span style="width:${Math.min(100,(g.loggedHours||0)/(g.targetHours||1)*100)}%"></span></div><div class="goal-signals"><span>기출점수 ${g.mockScore??"미입력"}</span><span>회독 ${g.rounds||0}회</span></div></div>`:'<div class="empty-state"><b>핵심 장기목표가 없습니다.</b><p>자격증 목표를 만들면 5번째 필수 퀘스트가 자동으로 연결됩니다.</p></div>';
 let keys=Object.keys(Q.days).filter(k=>Q.days[k].settled).sort().reverse(),recent=keys.slice(0,7),success=recent.reduce((s,k)=>s+(Q.days[k].result?.count||0),0),possible=recent.length*5;rhythm.innerHTML=`<div class="rhythm-score"><b>${possible?Math.round(success/possible*100):0}%</b><span>최근 ${recent.length||0}일 달성률</span></div><div class="mini-week">${recent.map(k=>`<div class="${(Q.days[k].result?.count||0)>=4?"strong":""}"><b>${Q.days[k].result?.count||0}</b><small>/5</small></div>`).join("")||"<p class='sub'>정산 기록이 아직 없습니다.</p>"}</div>`;
 let od=d.optional||[],done=d.optionalDone||[];optionalCount.textContent=`${od.length}/3 선택`;optionalList.innerHTML=OPTIONAL.map(q=>`<div class="optional-item ${od.includes(q.id)?"selected":""} ${done.includes(q.id)?"done":""}"><button class="optional-main" onclick="toggleOptional('${q.id}')"><b>${q.name}</b><small>+${q.xp} XP</small></button>${od.includes(q.id)&&!done.includes(q.id)?`<button class="primary smallbtn" onclick="completeOptional('${q.id}')">완료</button>`:done.includes(q.id)?'<span class="good">✓ 완료</span>':""}</div>`).join("");
 history14.innerHTML=Object.keys(Q.days).sort().reverse().slice(0,14).map(k=>{let x=Q.days[k];return `<div class="day-history"><b>${k}</b>${x.settled?`<span class="${x.result.count===5?"good":x.result.count>=3?"warn":"bad"}">${x.result.count}/5 · +${x.result.total} XP</span>`:'<span class="muted">미정산</span>'}</div>`}).join("");
 let p=pendingDay();settlementZone.innerHTML=p?`<div class="settlement-banner"><div><p class="eyebrow">READY TO SETTLE</p><h2>${p} 기록을 정산할 수 있습니다.</h2><p>5개 결과를 입력하면 자동 판정되고 XP가 한 번만 지급됩니다.</p></div><button class="primary" onclick="openSettlement('${p}')">어제 정산하기</button></div>`:"";
}
certName.innerHTML=certs.map(c=>`<option>${c.name}</option>`).join("");if([...certName.options].some(o=>o.value==="전기기사"))certName.value="전기기사";[certName,certStage,dailyHours,planDays].forEach(x=>x.onchange=previewGoal);previewGoal();
newGoalBtn.onclick=()=>goalBuilder.style.display="block";closeBuilder.onclick=()=>goalBuilder.style.display="none";createGoal.onclick=createLong;settleLater.onclick=()=>settleModal.style.display="none";render();
let pd=pendingDay();if(pd)setTimeout(()=>openSettlement(pd),250);
(function(){let suggested=sessionStorage.getItem("lifeSpecupSuggestedCert");if(suggested&&document.querySelector("#certName")){if([...certName.options].some(o=>o.value===suggested)){certName.value=suggested;goalBuilder.style.display="block";previewGoal()}sessionStorage.removeItem("lifeSpecupSuggestedCert")}})();
