const C=LifeSpecupCore,today=C.lifeDay();let Q=C.get("lifeSpecupQuests",{days:{},long:[],optionalSelected:[]}),S=C.get("lifeSpecupState",{xp:0,history:[]});Q.days=Q.days||{};Q.long=Q.long||[];S.history=S.history||[];
const certs=(window.CERTS||[]).map(c=>({...c,level:/기능장/.test(c.name)?"기능장":/기술사/.test(c.name)?"기술사":/산업기사/.test(c.name)?"산업기사":/기능사/.test(c.name)?"기능사":"기사"}));
function active(){return Q.long.find(x=>!x.done&&!x.paused)||Q.long.find(x=>!x.done)}function day(){return Q.days[today]||(Q.days[today]={simple:{done:false,hours:0,note:""},optionalDone:[]})}function save(){C.set("lifeSpecupQuests",Q);C.set("lifeSpecupState",S);render()}
function completeToday(){let g=active(),d=day();if(d.simple?.done)return C.toast("오늘 핵심 퀘스트는 이미 완료했습니다.");let h=Math.max(0,+todayHours.value||0);if(!g)return C.toast("먼저 장기 목표를 연결해주세요.");if(h<=0)return C.toast("실제 공부시간을 입력해주세요.");d.simple={done:true,hours:h,note:todayNote.value.trim(),goalId:g.id,at:new Date().toISOString()};g.loggedHours=(g.loggedHours||0)+h;g.studyDays=(g.studyDays||0)+1;g.lastStudyDay=today;let xp=Math.min(10,Math.max(2,Math.round(h*3)));S.xp=(S.xp||0)+xp;S.history.unshift({date:today,text:`🎯 ${g.cert} ${g.stage==="written"?"필기":"실기"} 공부 ${h}시간`,xp});save();C.toast(`오늘의 전진 완료 · +${xp} XP`)}
function createGoal(){let c=certs.find(x=>x.name===certName.value);if(!c)return;Q.long.filter(x=>!x.done).forEach(x=>x.paused=true);let h=+dailyHours.value||2,days=+planDays.value||60;Q.long.push({id:"goal-"+Date.now(),name:`${c.name} ${certStage.value==="written"?"필기":"실기"}`,cert:c.name,stage:certStage.value,dailyHours:h,days,targetHours:h*days,loggedHours:0,studyDays:0,started:today,done:false,paused:false});goalBuilder.style.display="none";save();C.toast("현실 목표와 오늘 퀘스트를 연결했습니다.")}
function render(){dayChip.textContent=`Life Day · ${today}`;let g=active(),d=day();coreFive.innerHTML=g?`<div class="one-quest ${d.simple?.done?"done":""}"><div><p class="eyebrow">TODAY'S ONE MOVE</p><h2>🎯 ${g.cert} ${g.stage==="written"?"필기":"실기"} 공부</h2><p>목표 ${g.dailyHours||2}시간 · 문제 수나 세부 항목은 입력하지 않아도 됩니다.</p></div>${d.simple?.done?`<strong>✓ ${d.simple.hours}시간 완료</strong>`:`<div class="quest-record"><label>실제 공부시간 <input id="todayHours" type="number" min="0" max="16" step=".5" value="${g.dailyHours||2}"></label><label>메모 <input id="todayNote" placeholder="선택사항"></label><button class="primary" id="completeTodayBtn">오늘 완료</button></div>`}</div>`:`<div class="empty-state"><b>오늘 연결된 핵심 목표가 없습니다.</b><p>자격증 목표를 하나 정하면 매일 단순한 공부시간 퀘스트로 이어집니다.</p></div>`;if(!d.simple?.done&&g)completeTodayBtn.onclick=completeToday;
 activeGoal.innerHTML=g?`<div class="active-goal-card"><span class="badge">${g.stage==="written"?"필기":"실기"}</span><h3>${g.cert}</h3><p>누적 ${g.loggedHours||0}시간 · 학습일 ${g.studyDays||0}일 · 하루 목표 ${g.dailyHours||2}시간</p><div class="progress"><span style="width:${Math.min(100,(g.loggedHours||0)/(g.targetHours||1)*100)}%"></span></div></div>`:'<div class="empty">진행 중인 장기 목표가 없습니다.</div>';
 rhythm.innerHTML=`<div class="rhythm-score"><b>${Object.values(Q.days).filter(x=>x.simple?.done).length}</b><span>누적 성장일</span></div><p class="sub">완벽한 하루보다 미래의 나를 향한 한 번의 실제 행동을 기록합니다.</p>`;optionalList.innerHTML=`<div class="optional-grid"><div class="optional-card"><b>🏃 운동</b><span>필요한 날만 기록</span></div><div class="optional-card"><b>💰 재정 점검</b><span>필요한 날만 기록</span></div><div class="optional-card"><b>📖 독서</b><span>필요한 날만 기록</span></div></div>`;optionalCount.textContent="선택";let hist=(S.history||[]).filter(x=>x.date).slice(0,14);history14.innerHTML=hist.map(x=>`<div class="history-row"><span>${x.date} · ${x.text}</span><b>+${x.xp||0} XP</b></div>`).join("")||'<div class="empty">아직 기록이 없습니다.</div>'}
newGoalBtn.onclick=()=>goalBuilder.style.display="block";closeBuilder.onclick=()=>goalBuilder.style.display="none";certName.innerHTML=certs.map(x=>`<option>${x.name}</option>`).join("");function preview(){goalPreview.innerHTML=`<b>${certName.value} ${certStage.value==="written"?"필기":"실기"}</b><p>매일 ${dailyHours.value}시간 · ${planDays.value}일. 세부 문제 수는 관리하지 않습니다.</p>`}certName.onchange=certStage.onchange=dailyHours.onchange=planDays.onchange=preview;createGoal.onclick=createGoal;preview();render();
