(()=>{'use strict';
const C=window.LifeSpecupCore;if(!C)return;const day=C.lifeDay();
function attendance(){let a=C.get('lifeSpecupAttendance',{days:[],last:null,streak:0,best:0});a.days=Array.isArray(a.days)?a.days:[];return a}
function dateDiff(a,b){return Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
function checkIn(){let a=attendance();if(a.days.includes(day))return {already:true,a};let prev=a.days.slice().sort().at(-1);a.streak=prev&&dateDiff(prev,day)===1?(a.streak||0)+1:1;a.best=Math.max(a.best||0,a.streak);a.days.push(day);a.days=[...new Set(a.days)].sort();a.last=day;C.set('lifeSpecupAttendance',a);C.saveXP(3,'오늘의 출석 · 성장 시스템 접속');evaluate();return {already:false,a}}
function studyHours(){let q=C.get('lifeSpecupQuests',{long:[]});return (q.long||[]).reduce((s,x)=>s+(+x.loggedHours||0),0)}
function careerMonths(){try{let u=window.LIFE_DATA?.loadUser?.()||{};return window.CAREER_STORE?.totalMonths?.(u)||Math.round((+u.careerYears||0)*12)}catch{return 0}}
function certs(){try{return new Set(window.LIFE_DATA?.certNames?.(window.LIFE_DATA.loadUser())||[])}catch{return new Set()}}
function qualifies(e){let a=attendance(),h=studyHours(),m=careerMonths(),cs=certs(),li=C.levelInfo(C.get('lifeSpecupState',{xp:0}).xp||0);let z;if((z=e.id.match(/^attendance-streak-(\d+)$/)))return (a.streak||0)>=+z[1];if((z=e.id.match(/^attendance-total-(\d+)$/)))return (a.days||[]).length>=+z[1];if((z=e.id.match(/^study-(\d+)$/)))return h>=+z[1];if(e.id==='career-3m')return m>=3;if(e.id==='career-6m')return m>=6;if(e.id==='career-12m')return m>=12;if(e.cert)return cs.has(e.cert);if(e.id==='double-electric')return cs.has('전기기사')&&cs.has('전기공사기사');if(e.id==='double-fire')return cs.has('소방설비기사(전기분야)')&&cs.has('소방설비기사(기계분야)');if(e.id==='level-10')return li.level>=10;if(e.id==='level-20')return li.level>=20;return false}
function evaluate(){if(!window.EMBLEMS)return[];let s=C.get('lifeSpecupEmblems',{owned:[],equipped:[]});s.owned=s.owned||[];s.equipped=s.equipped||[];let gained=[];EMBLEMS.forEach(e=>{if(!s.owned.includes(e.id)&&qualifies(e)){s.owned.push(e.id);gained.push(e);if(e.xp)C.saveXP(e.xp,`엠블렘 획득 · ${e.name}`)}});C.set('lifeSpecupEmblems',s);if(gained.length){let q=C.get('lifeSpecupAchievementQueue',[]);q.push(...gained.map(e=>e.id));C.set('lifeSpecupAchievementQueue',q)}return gained}
function showNext(){let q=C.get('lifeSpecupAchievementQueue',[]);if(!q.length||!window.EMBLEMS)return;let id=q.shift(),e=EMBLEMS.find(x=>x.id===id);C.set('lifeSpecupAchievementQueue',q);if(!e)return;let ov=document.createElement('div');ov.className='achievement-overlay';ov.innerHTML=`<div class="achievement-burst"></div><div class="achievement-modal"><p>ACHIEVEMENT UNLOCKED</p><div class="emblem-visual tone-${e.tone} achievement-emblem"><span>${e.icon}</span></div><small>${e.grade} · ${e.category}</small><h2>${e.name}</h2><div class="achievement-line"></div><p class="desc">${e.desc}</p><b>+${e.xp} XP</b><button>계속 성장하기</button></div>`;document.body.appendChild(ov);requestAnimationFrame(()=>ov.classList.add('show'));ov.querySelector('button').onclick=()=>{ov.classList.remove('show');setTimeout(()=>{ov.remove();showNext()},250)}}
window.LifeAchievements={attendance,checkIn,evaluate,showNext,careerMonths,studyHours};document.addEventListener('DOMContentLoaded',()=>{evaluate();setTimeout(showNext,250)});
})();