const C=LifeSpecupCore,D=CAREER_V2;let U=C.get("lifeSpecupUser",{}),V=C.get("lifeSpecupVerifiedCerts",[]),P=C.get("lifeSpecupCareerPrefs",{}),sim=new Set();
const roles=Object.keys(D.roles);role.innerHTML=roles.map(x=>`<option>${x}</option>`).join("");role.value=roles.includes(U.goalJob)?U.goalJob:"전기 시설관리";
companyTier.value=P.companyTier||(/대기업/.test(U.companyType||"")?"large":"mid");hireMode.value=P.hireMode||"career";roleLevel.value=P.roleLevel||"qualified";environment.value=P.environment||"building";
age.value=P.age||"";relatedYears.value=P.relatedYears??U.careerYears??0;toeic.value=P.toeic||0;opic.value=P.opic||"";majorRelated.value=P.majorRelated||"unknown";largeFacility.value=P.largeFacility||"none";
function baseCerts(){let a=new Set((U.certificates||[]).map(x=>x.name));V.filter(x=>x.status==="verified").forEach(x=>a.add(x.name));return a}
function allCerts(extra){let a=baseCerts();extra.forEach(x=>{if(!x.startsWith("_"))a.add(x)});return a}
function opicVal(x){return({"":0,IL:1,IM1:2,IM2:3,IM3:4,IH:5,AL:6})[x]||0}
function profile(extra=sim){return{age:+age.value||0,years:(+relatedYears.value||0)+(extra.has("_y1")?1:0)+(extra.has("_y2")?2:0),toeic:extra.has("_eng")?Math.max(800,+toeic.value||0):(+toeic.value||0),opic:opicVal(opic.value),major:majorRelated.value,facility:extra.has("_facility")?"strong":largeFacility.value,certs:allCerts(extra)}}
function requirements(extra=sim){let r=D.roles[role.value],co=D.company[companyTier.value],p=profile(extra),careerNeed=hireMode.value==="career"?r.careerCareer:r.entryCareer;if(roleLevel.value==="senior")careerNeed=Math.max(careerNeed,5);if(role.value==="데이터센터 전기시설")careerNeed=Math.max(careerNeed,hireMode.value==="career"?5:2);
let core=r.core.find(x=>p.certs.has(x)),synergy=r.synergy.filter(x=>p.certs.has(x)),englishNeed=co.english==="high"?700:co.english==="medium"?600:0,engOK=englishNeed===0||p.toeic>=englishNeed||p.opic>=2;
let items=[
{id:"core",name:"핵심 전기 자격",kind:"자격",hard:true,ok:!!core,current:core||"미보유",target:r.core.join(" 또는 "),weight:26},
{id:"career",name:"관련 실무경력",kind:"경력",hard:careerNeed>0,ok:p.years>=careerNeed,ratio:careerNeed?Math.min(1,p.years/careerNeed):1,current:`${p.years}년`,target:careerNeed?`${careerNeed}년 이상`:"경력무관 범위",weight:30},
{id:"synergy",name:"직무 시너지 자격",kind:"복수자격",hard:false,ok:synergy.length>=1,ratio:Math.min(1,synergy.length/2),current:synergy.join(" · ")||"없음",target:r.synergy.join(" · "),weight:12},
{id:"english",name:"어학",kind:"어학",hard:companyTier.value==="public",ok:engOK,current:p.toeic?`TOEIC ${p.toeic}`:opic.value?`OPIc ${opic.value}`:"미입력",target:englishNeed?`공고별 기준 · 모델 기준 TOEIC ${englishNeed}+`:"시설직 공통 필수 아님",weight:co.english==="low"?3:10},
{id:"major",name:"관련 전공·학력",kind:"학력",hard:false,ok:p.major==="yes",ratio:p.major==="yes"?1:p.major==="unknown"?.35:.15,current:p.major==="yes"?"관련 전공":p.major==="no"?"비관련 전공":"미입력",target:companyTier.value==="large"||companyTier.value==="public"?"관련 전공/학력 우대·요건 확인":"공고별 상이",weight:8},
{id:"facility",name:"현장 경험의 질",kind:"경험",hard:false,ok:p.facility==="strong",ratio:p.facility==="strong"?1:p.facility==="some"?.55:.1,current:p.facility==="strong"?"직접 운영":p.facility==="some"?"보조·일부":"미입력/없음",target:r.skills.join(" · "),weight:14}];
return{r,co,p,careerNeed,items}}
function calc(extra=sim){let x=requirements(extra),hard=x.items.filter(i=>i.hard),eligible=hard.length?Math.round(hard.filter(i=>i.ok).length/hard.length*100):100;
let raw=x.items.reduce((s,i)=>s+i.weight*(i.ok?1:(i.ratio||0)),0),competition=x.co.competition;
let trajectory=70;if(x.p.age){if(hireMode.value==="career"){let expected=Math.max(0,(x.p.age-25)*.35);if(x.p.years===0&&x.p.age>=35)trajectory=28;else if(x.p.years<Math.min(3,expected))trajectory=Math.max(35,65-Math.round((Math.min(3,expected)-x.p.years)*8));else trajectory=78}else{if(x.p.age>=35&&x.p.years===0)trajectory=42;else trajectory=72}}
let comp=Math.round(raw-competition);if(eligible<100)comp-=Math.round((100-eligible)*.18);if(hireMode.value==="career"&&x.p.years===0)comp=Math.min(comp,32);if(companyTier.value==="large"&&x.p.years<2&&hireMode.value==="career")comp=Math.min(comp,38);comp+=Math.round((trajectory-70)*.12);comp=Math.max(5,Math.min(92,comp));
return{...x,eligible,comp,trajectory,blockers:x.items.filter(i=>i.hard&&!i.ok)}}
function candidates(base){let ids=[...D.roles[role.value].core,...D.roles[role.value].synergy,"_y1","_y2","_eng","_facility"],labels={_y1:"관련경력 +1년",_y2:"관련경력 +2년",_eng:"어학 TOEIC 800 수준",_facility:"대형시설 직접운영 경험"};return ids.filter(id=>!sim.has(id)&&!base.p.certs.has(id)).map(id=>{let e=new Set(sim);e.add(id);let n=calc(e);return{id,label:labels[id]||id,delta:n.comp-base.comp,elig:n.eligible-base.eligible}}).filter(x=>x.delta>0||x.elig>0).sort((a,b)=>(b.elig-a.elig)||(b.delta-a.delta))}
function band(n){return n>=75?"강함":n>=60?"경쟁 가능":n>=45?"보완 필요":n>=30?"낮음":"매우 낮음"}
function render(){let r=calc(),opts=candidates(r);analysisArea.style.display="block";eligibility.textContent=r.eligible+"%";fitScore.textContent=r.comp+"/100";trajectory.textContent=r.trajectory+"/100";confidence.textContent=r.co.label==="중소·용역"?"보통":"보통";evidenceCount.textContent=`근거 ${D.evidence.length}건 · 규칙모델`;
let ageText=r.p.age?`만 ${r.p.age}세`:"나이 미입력";verdict.innerHTML=`<div class="career-verdict"><div><p class="eyebrow">AI INTERPRETATION</p><h2>${r.co.label} · ${hireMode.options[hireMode.selectedIndex].text} 기준 <span>${band(r.comp)}</span></h2><p>${ageText}, 관련경력 ${r.p.years}년. ${r.p.age>=35&&r.p.years===0?"나이 자체가 아니라 해당 연령대에서 관련경력이 0년인 ‘직무전환 궤적’이 경력직 경쟁에서 큰 불확실성으로 작용하도록 모델링했습니다.":r.p.years>=2?"관련경력 축이 형성되어 자격증 추가보다 경험의 질과 목표기업 맞춤성이 중요해집니다.":"관련경력 축이 아직 짧아 자격증 숫자만 늘리는 것보다 실제 직무경력을 쌓는 효과가 큽니다."}</p></div><div class="verdict-number"><small>COMPETITIVENESS</small><b>${r.comp}</b></div></div>`;
blocker.innerHTML=r.blockers.length?`<div class="blocker-box"><b>지원/경쟁의 핵심 BLOCKER</b><p>${r.blockers.map(x=>`${x.name}: ${x.current} → ${x.target}`).join("<br>")}</p><small>다른 우대 스펙이 많아도 필수 경력·자격 부족을 완전히 상쇄하지 않도록 계산합니다.</small></div>`:`<div class="ready-box">✓ 입력정보 기준 핵심 지원조건은 충족했습니다. 아래 경쟁력 요소를 비교하세요.</div>`;
requirements.innerHTML=r.items.map(i=>`<div class="req-row"><div class="req-state ${i.ok?"met":i.hard?"blocked":"gap"}">${i.ok?"✓":i.hard?"!":"△"}</div><div class="req-body"><div class="row-head"><b>${i.name}</b><span class="source-tag">${i.hard?"지원조건/핵심":"경쟁력"}</span></div><div class="req-compare"><span>${i.current}</span><i>→</i><strong>${i.target}</strong></div></div><em>${i.ok?"충족":i.hard?"BLOCKER":"보완"}</em></div>`).join("");
roadmap.innerHTML=opts.slice(0,5).map((o,i)=>`<div class="road-step"><span>${i+1}</span><div><b>${o.label}</b><p>${o.elig?`지원조건 +${o.elig}% · `:""}경쟁력 +${o.delta} 예상</p></div>${!o.id.startsWith("_")?`<button class="secondary smallbtn" onclick="startGoal('${o.id}')">목표로</button>`:""}</div>`).join("")||'<div class="empty">현재 모델에서 큰 단일 격차가 없습니다.</div>';
simOptions.innerHTML=opts.slice(0,7).map(o=>`<button class="sim-chip" onclick="toggleSim('${o.id}')">${o.label} <small>+${o.delta}</small></button>`).join("");let clean=calc(new Set());beforeScore.textContent=clean.comp;afterScore.textContent=r.comp;simDelta.textContent=sim.size?`가상 변화 ${r.comp-clean.comp>=0?"+":""}${r.comp-clean.comp}점`:"스펙을 선택해 미래 상태를 비교하세요.";
evidence.innerHTML=D.evidence.map(e=>`<div class="evidence-row"><span>${e.type}</span><div><b>${e.title}</b><p>${e.detail}</p></div><a href="${e.url}" target="_blank" rel="noopener">근거 보기 ↗</a></div>`).join("");
profileMini.innerHTML=`<p class="eyebrow">TARGET MODEL</p><h3>${r.co.label}</h3><p>${hireMode.options[hireMode.selectedIndex].text} · ${roleLevel.options[roleLevel.selectedIndex].text}</p><small>점수는 합격확률이 아닙니다.</small>`}
function persist(){P={...P,companyTier:companyTier.value,hireMode:hireMode.value,roleLevel:roleLevel.value,environment:environment.value,age:+age.value||0,relatedYears:+relatedYears.value||0,toeic:+toeic.value||0,opic:opic.value,majorRelated:majorRelated.value,largeFacility:largeFacility.value};C.set("lifeSpecupCareerPrefs",P);U.goalJob=role.value;C.set("lifeSpecupUser",U)}
function toggleSim(id){sim.has(id)?sim.delete(id):sim.add(id);render()}function startGoal(n){sessionStorage.setItem("lifeSpecupSuggestedCert",n);location.href="quests.html"}
resetSim.onclick=()=>{sim.clear();render()};analyze.onclick=()=>{persist();sim.clear();render()};saveProfile.onclick=()=>{persist();C.toast("경쟁력 정보를 저장했습니다.");render()};[role,roleLevel,environment,companyTier,hireMode].forEach(x=>x.onchange=()=>{if(analysisArea.style.display!=="none"){sim.clear();render()}});render();