const fmtCareer=y=>{let m=Math.max(0,Math.round((+y||0)*12)),yr=Math.floor(m/12),mo=m%12;return yr?(mo?`${yr}년 ${mo}개월`:`${yr}년`):`${mo}개월`};
const C=LifeSpecupCore,U=LIFE_DATA.loadUser(),S=C.get("lifeSpecupState",{xp:0,history:[]}),Q=C.get("lifeSpecupQuests",{days:{},long:[]}),F=C.get("lifeSpecupFinance",{}),V=C.get("lifeSpecupVerifiedCerts",[]),B=TargetBuild.load();
const fmt=n=>Math.round(+n||0).toLocaleString("ko-KR")+"원",today=C.lifeDay(),D=Q.days?.[today]||{};
helloName.textContent=U.nickname||"플레이어";lifeDate.textContent=`Life Day ${today} · 오늘 할 일은 단순하게, 현실 성장은 길게 기록합니다.`;
let active=(Q.long||[]).find(x=>!x.done&&!x.paused)||(Q.long||[]).find(x=>!x.done);
let moves=C.get("lifeSpecupOneMoves",[]),moveIndex=0;if(!moves.length&&active)moves=[{id:"goal-"+(active.id||"main"),title:(active.cert||active.name)+" "+(active.stage==="written"?"필기":"실기"),note:"오늘 "+(active.dailyHours||2)+"시간 · 누적 "+(active.loggedHours||0)+"시간",linked:true}];
const escMove=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function saveMoves(){C.set("lifeSpecupOneMoves",moves)}
function addMove(){let title=prompt("오늘의 One Move를 입력하세요.\\n예: 소방실기 단답 30문제");if(!title||!title.trim())return;let note=prompt("짧은 메모 (선택)","오늘 끝내면 충분합니다.")||"";moves.push({id:"m"+Date.now(),title:title.trim(),note:note.trim(),createdAt:new Date().toISOString()});saveMoves();moveIndex=moves.length-1;renderMoves()}
function renderMoves(){if(!moves.length){focusCard.innerHTML='<article class="one-move-card"><span class="move-no">01</span><div class="move-content"><small>START TODAY</small><h3>오늘의 One Move를 추가해보세요.</h3><p>오늘 꼭 움직일 한 가지면 충분합니다.</p></div><div class="move-actions"><button class="primary" id="emptyMoveAdd">＋ 추가하기</button></div></article>';oneMoveCount.textContent="0 / 0";oneMoveDots.innerHTML="";oneMovePrev.disabled=oneMoveNext.disabled=true;document.getElementById("emptyMoveAdd").onclick=addMove;return}moveIndex=Math.max(0,Math.min(moveIndex,moves.length-1));focusCard.innerHTML=moves.map((m,i)=>'<article class="one-move-card"><span class="move-no">'+String(i+1).padStart(2,"0")+'</span><div class="move-content"><small>'+(m.linked?"ACTIVE GOAL":"PERSONAL MOVE")+'</small><h3>'+escMove(m.title)+'</h3><p>'+escMove(m.note||"오늘 끝내면 충분합니다.")+'</p></div><div class="move-actions">'+(m.linked?'<button class="primary" onclick="location.href=\'quests.html\'">기록하기</button>':'<button class="primary">집중하기</button><button class="ghost move-delete" data-del="'+i+'">삭제</button>')+'</div></article>').join("");focusCard.style.transform="translateX(-"+(moveIndex*100)+"%)";oneMoveCount.textContent=(moveIndex+1)+" / "+moves.length;oneMoveDots.innerHTML=moves.map((_,i)=>'<button class="'+(i===moveIndex?"active":"")+'" data-dot="'+i+'"></button>').join("");oneMovePrev.disabled=moveIndex===0;oneMoveNext.disabled=moveIndex===moves.length-1;focusCard.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{moves.splice(+b.dataset.del,1);saveMoves();if(moveIndex>=moves.length)moveIndex=Math.max(0,moves.length-1);renderMoves()})}
oneMoveAdd.onclick=addMove;oneMovePrev.onclick=()=>{if(moveIndex>0){moveIndex--;renderMoves()}};oneMoveNext.onclick=()=>{if(moveIndex<moves.length-1){moveIndex++;renderMoves()}};oneMoveDots.onclick=e=>{let b=e.target.closest("[data-dot]");if(b){moveIndex=+b.dataset.dot;renderMoves()}};let touchX=0;focusCard.addEventListener("touchstart",e=>touchX=e.touches[0].clientX,{passive:true});focusCard.addEventListener("touchend",e=>{let dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>45){if(dx<0&&moveIndex<moves.length-1)moveIndex++;else if(dx>0&&moveIndex>0)moveIndex--;renderMoves()}},{passive:true});renderMoves();
let pct=TargetBuild.progress(B),owned=TargetBuild.owned(),curY=TargetBuild.currentYears(),missing=TargetBuild.missing(B),targetCerts=[...new Set([...owned,...(B.certs||[]).map(x=>x.name||x)])];
targetBuildHome.innerHTML=(B.careerYears||B.certs?.length)?`<div class="build-hero"><div class="build-ring" style="--p:${pct}"><b>${pct}%</b><small>BUILD</small></div><div class="build-body"><div class="build-path"><span>NOW</span><b>관련경력 ${fmtCareer(curY)} · ${[...owned].join(' · ')||'자격 없음'}</b><i>→</i><span>TARGET</span><b>관련경력 ${fmtCareer(B.careerYears||curY)} · ${targetCerts.join(' · ')||'목표 자격 미설정'}</b></div><div class="progress"><span style="width:${pct}%"></span></div><p>${missing.length?`다음 현실 성취: <b>${missing[0].name||missing[0]}</b>`:'설정한 자격 목표를 달성했습니다. 다음 미래를 설계할 차례입니다.'}</p></div></div>`:`<div class="empty-state"><b>아직 미래의 내가 없습니다.</b><p>AI 커리어에서 “1년 뒤의 나”를 먼저 만들어 보세요. 그 모습이 홈과 퀘스트의 목적지가 됩니다.</p><button class="primary" onclick="location.href='career.html'">미래의 나 만들기</button></div>`;
let todayDone=!!D.simple?.done;todayRate.textContent=todayDone?"오늘 완료":"오늘";todayActions.innerHTML=active?`<div class="action-line hero-action"><span>${todayDone?'✓':'○'}</span><div><b>🎯 ${active.cert||active.name} ${active.stage==="written"?"필기":"실기"} 공부</b><small>${todayDone?`실제 ${D.simple.hours}시간 완료`:`목표 ${active.dailyHours||2}시간 · 세부 문제수 입력 불필요`}</small></div><em>${todayDone?'완료':'핵심'}</em></div>`:`<div class="empty">오늘 연결된 핵심 퀘스트가 없습니다.</div>`;
if(active){let gp=Math.min(100,Math.round((active.loggedHours||0)/(active.targetHours||1)*100));goalProgress.innerHTML=`<div class="goal-title"><b>${active.name}</b><span>${gp}%</span></div><div class="progress"><span style="width:${gp}%"></span></div><div class="goal-signals"><span>누적 ${active.loggedHours||0}h</span><span>학습일 ${active.studyDays||0}일</span><span>현재 단계 ${active.stage==="written"?"필기":"실기"}</span></div>`}else goalProgress.innerHTML='<div class="empty">진행 중인 목표가 없습니다.</div>';
currentPath.textContent=`관련경력 ${fmtCareer(curY)} · ${[...owned].join(' · ')||'자격 없음'}`;targetPath.textContent=(B.careerYears||B.certs?.length)?`관련경력 ${fmtCareer(B.careerYears||curY)} · ${targetCerts.join(' · ')}`:"미래 목표 미설정";gapHint.innerHTML=missing.length?`<b>지금 가장 가까운 빈칸</b><br>${missing.slice(0,2).map(x=>x.name||x).join(" · ")} · 하루 행동은 단순하게 기록하고, 실제 취득 때 미래 빌드가 크게 채워집니다.`:`<b>현실 성취와 목표가 연결되어 있습니다.</b>`;
let li=C.levelInfo(S.xp||0);level.textContent=li.level;levelBar.style.width=li.pct+"%";levelXp.textContent=`${li.cur}/${li.need} XP · ${li.level%10===0?"MILESTONE LEVEL":"다음 마일스톤 LV."+(Math.ceil(li.level/10)*10)}`;certCount.textContent=owned.size+"개";
let assets=(F.deposits||[]).reduce((s,x)=>s+(+x.amount||0),0)+(F.stocks||[]).reduce((s,x)=>s+(+x.amount||0),0)+(F.housing||[]).reduce((s,x)=>s+(+x.assetValue||0)+(+x.deposit||0),0),debt=(F.debts||[]).reduce((s,x)=>s+(+x.balance||0),0);netWorth.textContent=fmt(assets-debt);monthlyFlow.textContent="현실 자산 기준";
let keys=Object.keys(Q.days||{}).sort().reverse().slice(0,7),sum=keys.filter(k=>Q.days[k]?.simple?.done).length;weekRate.textContent=(keys.length?Math.round(sum/keys.length*100):0)+"%";recentHistory.innerHTML=(S.history||[]).slice(0,6).map(h=>`<div class="history-row"><span>${h.text}</span><b>${h.xp?`+${h.xp} XP`:""}</b></div>`).join("")||'<div class="empty">아직 성장 기록이 없습니다.</div>';

const milestones=[{lv:10,name:"첫 성장기",unlock:"첫 마일스톤 기록"},{lv:20,name:"루트 개척자",unlock:"꾸준함 휘장"},{lv:30,name:"스펙 빌더",unlock:"빌드 기록 휘장"},{lv:40,name:"현실 전직",unlock:"커리어 챕터 휘장"},{lv:50,name:"CHAPTER II",unlock:"장기 성장 휘장"}];milestoneRoad.innerHTML=milestones.map(m=>`<div class="milestone ${li.level>=m.lv?"reached":""}"><b>LV.${m.lv}</b><span>${m.name}</span><small>${li.level>=m.lv?"✓ 달성":"기록 · "+m.unlock}</small></div>`).join("");
