const fmtCareer=y=>{let m=Math.max(0,Math.round((+y||0)*12)),yr=Math.floor(m/12),mo=m%12;return yr?(mo?`${yr}년 ${mo}개월`:`${yr}년`):`${mo}개월`};
const C=LifeSpecupCore,U=LIFE_DATA.loadUser(),S=C.get("lifeSpecupState",{xp:0,history:[]}),Q=C.get("lifeSpecupQuests",{days:{},long:[]}),F=C.get("lifeSpecupFinance",{}),V=C.get("lifeSpecupVerifiedCerts",[]),B=TargetBuild.load();
const fmt=n=>Math.round(+n||0).toLocaleString("ko-KR")+"원",today=C.lifeDay(),D=Q.days?.[today]||{};
helloName.textContent=U.nickname||"플레이어";lifeDate.textContent=`Life Day ${today} · 오늘 할 일은 단순하게, 현실 성장은 길게 기록합니다.`;
let active=(Q.long||[]).find(x=>!x.done&&!x.paused)||(Q.long||[]).find(x=>!x.done);
if(active){let pct=Math.min(100,Math.round((active.loggedHours||0)/(active.targetHours||1)*100));focusCard.innerHTML=`<div><p class="eyebrow">TODAY'S ONE MOVE</p><h2>${active.cert||active.name} ${active.stage==="written"?"필기":"실기"}</h2><p>오늘은 <b>${active.dailyHours||2}시간 공부</b>면 충분합니다. · 누적 ${active.loggedHours||0}시간</p></div><div class="focus-progress"><div class="progress"><span style="width:${pct}%"></span></div><button class="primary" onclick="location.href='quests.html'">오늘 기록하기</button></div>`}else focusCard.innerHTML=`<div><p class="eyebrow">TODAY'S ONE MOVE</p><h2>오늘의 핵심 행동을 정하세요.</h2><p>목표 자격증을 연결하면 매일 “공부 2시간”처럼 단순한 퀘스트 하나로 이어집니다.</p></div><button class="primary" onclick="location.href='quests.html'">목표 연결하기</button>`;
let pct=TargetBuild.progress(B),owned=TargetBuild.owned(),curY=TargetBuild.currentYears(),missing=TargetBuild.missing(B),targetCerts=[...new Set([...owned,...(B.certs||[]).map(x=>x.name||x)])];
targetBuildHome.innerHTML=(B.careerYears||B.certs?.length)?`<div class="build-hero"><div class="build-ring" style="--p:${pct}"><b>${pct}%</b><small>BUILD</small></div><div class="build-body"><div class="build-path"><span>NOW</span><b>관련경력 ${fmtCareer(curY)} · ${[...owned].join(' · ')||'자격 없음'}</b><i>→</i><span>TARGET</span><b>관련경력 ${fmtCareer(B.careerYears||curY)} · ${targetCerts.join(' · ')||'목표 자격 미설정'}</b></div><div class="progress"><span style="width:${pct}%"></span></div><p>${missing.length?`다음 현실 성취: <b>${missing[0].name||missing[0]}</b>`:'설정한 자격 목표를 달성했습니다. 다음 미래를 설계할 차례입니다.'}</p></div></div>`:`<div class="empty-state"><b>아직 미래의 내가 없습니다.</b><p>AI 커리어에서 “1년 뒤의 나”를 먼저 만들어 보세요. 그 모습이 홈과 퀘스트의 목적지가 됩니다.</p><button class="primary" onclick="location.href='career.html'">미래의 나 만들기</button></div>`;
let todayDone=!!D.simple?.done;todayRate.textContent=todayDone?"오늘 완료":"오늘";todayActions.innerHTML=active?`<div class="action-line hero-action"><span>${todayDone?'✓':'○'}</span><div><b>🎯 ${active.cert||active.name} ${active.stage==="written"?"필기":"실기"} 공부</b><small>${todayDone?`실제 ${D.simple.hours}시간 완료`:`목표 ${active.dailyHours||2}시간 · 세부 문제수 입력 불필요`}</small></div><em>${todayDone?'완료':'핵심'}</em></div>`:`<div class="empty">오늘 연결된 핵심 퀘스트가 없습니다.</div>`;
if(active){let gp=Math.min(100,Math.round((active.loggedHours||0)/(active.targetHours||1)*100));goalProgress.innerHTML=`<div class="goal-title"><b>${active.name}</b><span>${gp}%</span></div><div class="progress"><span style="width:${gp}%"></span></div><div class="goal-signals"><span>누적 ${active.loggedHours||0}h</span><span>학습일 ${active.studyDays||0}일</span><span>현재 단계 ${active.stage==="written"?"필기":"실기"}</span></div>`}else goalProgress.innerHTML='<div class="empty">진행 중인 목표가 없습니다.</div>';
currentPath.textContent=`관련경력 ${fmtCareer(curY)} · ${[...owned].join(' · ')||'자격 없음'}`;targetPath.textContent=(B.careerYears||B.certs?.length)?`관련경력 ${fmtCareer(B.careerYears||curY)} · ${targetCerts.join(' · ')}`:"미래 목표 미설정";gapHint.innerHTML=missing.length?`<b>지금 가장 가까운 빈칸</b><br>${missing.slice(0,2).map(x=>x.name||x).join(" · ")} · 하루 행동은 단순하게 기록하고, 실제 취득 때 미래 빌드가 크게 채워집니다.`:`<b>현실 성취와 목표가 연결되어 있습니다.</b>`;
let li=C.levelInfo(S.xp||0);level.textContent=li.level;levelBar.style.width=li.pct+"%";levelXp.textContent=`${li.cur}/${li.need} XP · ${li.level%10===0?"MILESTONE LEVEL":"다음 마일스톤 LV."+(Math.ceil(li.level/10)*10)}`;certCount.textContent=owned.size+"개";
let assets=(F.deposits||[]).reduce((s,x)=>s+(+x.amount||0),0)+(F.stocks||[]).reduce((s,x)=>s+(+x.amount||0),0)+(F.housing||[]).reduce((s,x)=>s+(+x.assetValue||0)+(+x.deposit||0),0),debt=(F.debts||[]).reduce((s,x)=>s+(+x.balance||0),0);netWorth.textContent=fmt(assets-debt);monthlyFlow.textContent="현실 자산 기준";
let keys=Object.keys(Q.days||{}).sort().reverse().slice(0,7),sum=keys.filter(k=>Q.days[k]?.simple?.done).length;weekRate.textContent=(keys.length?Math.round(sum/keys.length*100):0)+"%";recentHistory.innerHTML=(S.history||[]).slice(0,6).map(h=>`<div class="history-row"><span>${h.text}</span><b>${h.xp?`+${h.xp} XP`:""}</b></div>`).join("")||'<div class="empty">아직 성장 기록이 없습니다.</div>';

const milestones=[{lv:10,name:"첫 성장기",unlock:"첫 마일스톤 기록"},{lv:20,name:"루트 개척자",unlock:"꾸준함 휘장"},{lv:30,name:"스펙 빌더",unlock:"빌드 기록 휘장"},{lv:40,name:"현실 전직",unlock:"커리어 챕터 휘장"},{lv:50,name:"CHAPTER II",unlock:"장기 성장 휘장"}];milestoneRoad.innerHTML=milestones.map(m=>`<div class="milestone ${li.level>=m.lv?"reached":""}"><b>LV.${m.lv}</b><span>${m.name}</span><small>${li.level>=m.lv?"✓ 달성":"기록 · "+m.unlock}</small></div>`).join("");
