(()=>{'use strict';
const C=window.LifeSpecupCore;if(!C)throw new Error('LifeSpecupCore not loaded');
const el=id=>document.getElementById(id),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=C.lifeDay();let Q=C.get('lifeSpecupQuests',{days:{},long:[]})||{},S=C.get('lifeSpecupState',{xp:0,history:[]})||{};Q.days=Q.days||{};Q.long=Q.long||[];S.history=S.history||[];
const certs=(window.CERTS||[]).map(c=>({...c}));const R={day:el('dayChip'),core:el('coreFive'),build:el('buildMini'),road:el('questRoad'),badge:el('roadBadge'),active:el('activeGoal'),rhythm:el('rhythm'),builder:el('goalBuilder'),cert:el('certName'),stage:el('certStage'),hours:el('dailyHours'),days:el('planDays'),preview:el('goalPreview'),history:el('history14')};
function active(){return Q.long.find(x=>!x.done&&!x.paused)||Q.long.find(x=>!x.done)||null}function day(){return Q.days[today]||(Q.days[today]={simple:{done:false,hours:0,note:''}})}function persist(){C.set('lifeSpecupQuests',Q);C.set('lifeSpecupState',S)}
function syncTarget(cert,stage){if(!window.TargetBuild)return;let b=TargetBuild.load(),arr=b.certs||[],i=arr.findIndex(x=>(typeof x==='string'?x:x.name)===cert),state=stage==='practical'?'written_pass':'target';if(i<0)arr.push({name:cert,stage:state});else if(typeof arr[i]==='object'&&stage==='practical')arr[i].stage='written_pass';b.certs=arr;b.createdAt=b.createdAt||new Date().toISOString();TargetBuild.save(b)}
function completeToday(){let g=active(),d=day();if(!g)return C.toast('먼저 목표를 시작해주세요.');if(d.simple?.done)return C.toast('오늘 기록은 이미 완료했습니다.');let h=Math.max(0,+el('todayHours')?.value||0);if(!h)return C.toast('공부시간을 입력해주세요.');d.simple={done:true,hours:h,note:(el('todayNote')?.value||'').trim(),goalId:g.id,at:new Date().toISOString()};g.loggedHours=(+g.loggedHours||0)+h;if(g.lastStudyDay!==today){g.studyDays=(+g.studyDays||0)+1;g.lastStudyDay=today}let xp=Math.min(12,Math.max(3,Math.round(h*3)));S.xp=(+S.xp||0)+xp;S.history.unshift({id:`study-${today}-${g.id}`,date:today,text:`${g.cert} ${g.stage==='written'?'필기':'실기'} · ${h}시간 집중`,xp});persist();if(window.LifeAchievements){LifeAchievements.evaluate();setTimeout(LifeAchievements.showNext,700)}document.body.classList.add('quest-cleared');setTimeout(()=>document.body.classList.remove('quest-cleared'),900);render();C.toast(`QUEST CLEAR · ${h}시간의 증거 +${xp} XP`)}
function createGoal(){let c=certs.find(x=>x.name===R.cert.value);if(!c)return C.toast('자격증을 선택해주세요.');Q.long.filter(x=>!x.done).forEach(x=>x.paused=true);let h=Math.max(.5,+R.hours.value||2),days=Math.max(1,+R.days.value||60),stage=R.stage.value==='written'?'written':'practical';Q.long.push({id:`goal-${Date.now()}`,name:`${c.name} ${stage==='written'?'필기':'실기'}`,cert:c.name,stage,dailyHours:h,days,targetHours:h*days,loggedHours:0,studyDays:0,started:today,done:false,paused:false});syncTarget(c.name,stage);R.builder.style.display='none';persist();render();C.toast('캠페인을 시작했습니다. 오늘의 행동과 연결됐습니다.')}
function openBuilder(){R.builder.style.display='block';let s=sessionStorage.getItem('lifeSpecupSuggestedCert');if(s&&certs.some(x=>x.name===s))R.cert.value=s;preview();R.builder.scrollIntoView({behavior:'smooth',block:'center'})}
function render(){let g=active(),d=day(),b=window.TargetBuild?TargetBuild.load():null,p=window.TargetBuild?TargetBuild.progress(b):0;R.day.textContent=`${today} · LIFE DAY`;R.build.innerHTML=b?`<div class="mini-build-score"><b>${p}%</b><span>미래 빌드 완성도</span></div><strong>${safe(b.name||'미래의 나')}</strong><p>${(b.certs||[]).length}개 자격 목표 · 경력 ${(+b.careerYears||0).toFixed(1)}년 목표</p>`:`<p>아직 미래 빌드가 없습니다.</p>`;
if(!g){R.core.innerHTML=`<h2>아직 오늘의 메인 퀘스트가 없습니다.</h2><p>먼저 현실 목표 하나를 연결하세요. 그 다음부터 앱이 오늘 해야 할 행동만 보여줍니다.</p><button class="primary" id="emptyStartBtn">첫 목표 연결</button>`;R.road.innerHTML='<div class="road-empty">목표를 시작하면 현실 단계가 여기에 이어집니다.</div>';R.active.innerHTML='<div class="empty">진행 중인 목표가 없습니다.</div>';R.rhythm.innerHTML='<div class="momentum-zero"><b>0</b><span>아직 첫 기록 전</span></div>';el('emptyStartBtn')?.addEventListener('click',openBuilder)}else{let target=Math.max(1,+g.targetHours||1),pct=Math.min(100,Math.round((+g.loggedHours||0)/target*100)),done=!!d.simple?.done;R.core.innerHTML=`<div class="mission-kicker"><span>${g.stage==='written'?'WRITTEN':'PRACTICAL'}</span><i>${pct}% CAMPAIGN</i></div><h2>${safe(g.cert)} <em>${g.stage==='written'?'필기':'실기'}</em></h2><p class="mission-why">오늘의 임무는 단 하나. <b>${g.dailyHours||2}시간 집중</b>해서 합격에 필요한 실제 공부량을 쌓는 것.</p><div class="mission-progress"><span style="width:${pct}%"></span></div>${done?`<div class="clear-banner"><span>✓</span><div><b>오늘의 증거 확보</b><small>${d.simple.hours}시간 집중 완료 · 내일 다시 이어집니다.</small></div></div>`:`<div class="mission-action"><label><span>오늘 실제 공부</span><div><input id="todayHours" type="number" min=".5" max="16" step=".5" value="${g.dailyHours||2}"><b>시간</b></div></label><label class="mission-note"><span>한 줄 기록 <i>선택</i></span><input id="todayNote" placeholder="예: 기출 2024년까지 진행"></label><button class="primary clear-btn" id="completeTodayBtn">QUEST CLEAR</button></div>`}`;el('completeTodayBtn')?.addEventListener('click',completeToday);
let stages=g.stage==='practical'?[['필기 합격',true,'현실 성취'],['실기 준비',true,`${g.studyDays||0}일 · ${g.loggedHours||0}h`],['실기 시험',false,'시험 응시'],['최종 합격',false,'결과 확인'],['자격 취득',false,'BUILD COMPLETE']]:[['필기 준비',true,`${g.studyDays||0}일 · ${g.loggedHours||0}h`],['필기 시험',false,'시험 응시'],['필기 합격',false,'결과 확인'],['실기 준비',false,'NEXT STAGE'],['자격 취득',false,'BUILD COMPLETE']];R.road.innerHTML=`<div class="road-line">${stages.map((x,i)=>`<div class="road-node ${x[1]?'active':''}"><span>${x[1]?'✓':i+1}</span><b>${x[0]}</b><small>${x[2]}</small></div>`).join('<i></i>')}</div>`;R.badge.textContent=`${pct}% 진행`;
R.active.innerHTML=`<div class="campaign-card"><div><span class="badge">${g.stage==='written'?'필기':'실기'} CAMPAIGN</span><h3>${safe(g.cert)}</h3><p>${g.started} 시작 · ${g.studyDays||0}일 공부 · 누적 ${g.loggedHours||0}시간</p></div><div class="campaign-stat"><b>${pct}%</b><span>${Math.max(0,target-(+g.loggedHours||0)).toFixed(1)}h 남음</span></div></div>`;let doneDays=Object.values(Q.days).filter(x=>x.simple?.done).length;R.rhythm.innerHTML=`<div class="momentum"><div><b>${doneDays}</b><span>성장일</span></div><div><b>${g.studyDays||0}</b><span>이 목표 학습일</span></div><div><b>${g.loggedHours||0}h</b><span>누적 집중</span></div></div><p class="sub">체크 수가 아니라 실제로 투자한 시간이 쌓입니다.</p>`}
let hist=(S.history||[]).filter(x=>x.date).slice(0,8);R.history.innerHTML=hist.length?hist.map(x=>`<div class="journey-row"><span class="journey-dot"></span><div><b>${safe(x.text)}</b><small>${safe(x.date)}</small></div><strong>+${+x.xp||0} XP</strong></div>`).join(''):'<div class="empty">첫 QUEST CLEAR가 여기에 기록됩니다.</div>'}
function preview(){R.preview.innerHTML=`<b>${safe(R.cert.value)} · ${R.stage.value==='written'?'필기 준비':'필기 합격 → 실기 준비'}</b><p>하루 ${R.hours.value}시간을 ${R.days.value}일 동안 핵심 행동으로 연결합니다. 실제 합격 여부는 공부 기록과 별도로 관리합니다.</p>`}
R.cert.innerHTML=certs.map(x=>`<option value="${safe(x.name)}">${safe(x.name)}</option>`).join('');el('newGoalBtn').addEventListener('click',openBuilder);el('closeBuilder').addEventListener('click',()=>R.builder.style.display='none');el('createGoal').addEventListener('click',createGoal);[R.cert,R.stage,R.hours,R.days].forEach(x=>x.addEventListener('change',preview));preview();render();})();
