(()=>{'use strict';
const C=window.LifeSpecupCore;if(!C)throw new Error('LifeSpecupCore not loaded');
const el=id=>document.getElementById(id),safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=C.lifeDay();let Q=C.get('lifeSpecupQuests',{days:{},long:[]})||{},S=C.get('lifeSpecupState',{xp:0,history:[]})||{};Q.days=Q.days||{};Q.long=Q.long||[];S.history=S.history||[];
const certs=(window.CERTS||[]).map(c=>({...c}));const R={day:el('dayChip'),core:el('coreFive'),build:el('buildMini'),road:el('questRoad'),badge:el('roadBadge'),active:el('activeGoal'),rhythm:el('rhythm'),builder:el('goalBuilder'),cert:el('certName'),stage:el('certStage'),hours:el('dailyHours'),mins:el('dailyMinutes'),exam:el('examDate'),focus:el('focusPeriod'),preview:el('goalPreview'),history:el('history14')};
function active(){return Q.long.find(x=>!x.done&&!x.paused)||Q.long.find(x=>!x.done)||null}
function day(){let d=Q.days[today]||(Q.days[today]={simple:{done:false,hours:0,note:''}});d.sessions=d.sessions||[];return d}
function persist(){C.set('lifeSpecupQuests',Q);C.set('lifeSpecupState',S)}
function dateDays(v){if(!v)return null;let a=new Date(today+'T00:00:00'),b=new Date(v+'T00:00:00');return Math.ceil((b-a)/86400000)}
function fmtHours(h){let m=Math.round((+h||0)*60),hh=Math.floor(m/60),mm=m%60;return hh&&mm?`${hh}시간 ${mm}분`:hh?`${hh}시간`:`${mm}분`}
function inputHours(hid='todayHours',mid='todayMinutes'){return Math.max(0,(+el(hid)?.value||0)+(+el(mid)?.value||0)/60)}
function targetDaily(){return Math.max(0,(+R.hours.value||0)+(+R.mins.value||0)/60)}
function todayTotal(d=day()){return (d.sessions||[]).reduce((a,x)=>a+(+x.hours||0),0) || (+d.simple?.hours||0)}
function syncTarget(cert,stage){if(!window.TargetBuild)return;let b=TargetBuild.load(),arr=b.certs||[],i=arr.findIndex(x=>(typeof x==='string'?x:x.name)===cert),state=stage==='practical'?'written_pass':'target';if(i<0)arr.push({name:cert,stage:state});else if(typeof arr[i]==='object'&&stage==='practical')arr[i].stage='written_pass';b.certs=arr;b.createdAt=b.createdAt||new Date().toISOString();TargetBuild.save(b)}
function recordStudy(extra=false){let g=active(),d=day();if(!g)return C.toast('먼저 목표를 시작해주세요.');let h=inputHours(extra?'extraHours':'todayHours',extra?'extraMinutes':'todayMinutes');if(h<=0)return C.toast('공부시간을 입력해주세요.');let note=(el(extra?'extraNote':'todayNote')?.value||'').trim(),first=!d.simple?.done;d.sessions.push({hours:h,note,goalId:g.id,at:new Date().toISOString(),extra:!first});d.simple={done:true,hours:todayTotal(d),note:note||d.simple?.note||'',goalId:g.id,at:new Date().toISOString()};g.loggedHours=(+g.loggedHours||0)+h;if(g.lastStudyDay!==today){g.studyDays=(+g.studyDays||0)+1;g.lastStudyDay=today}let xp=first?Math.min(12,Math.max(3,Math.round(h*3))):0;if(xp)S.xp=(+S.xp||0)+xp;S.history.unshift({id:`study-${Date.now()}-${g.id}`,date:today,text:`${g.cert} ${g.stage==='written'?'필기':'실기'} · ${fmtHours(h)}${first?' 집중':' 추가 공부'}`,xp});persist();if(window.LifeAchievements){LifeAchievements.evaluate();setTimeout(LifeAchievements.showNext,500)}if(first){document.body.classList.add('quest-cleared');setTimeout(()=>document.body.classList.remove('quest-cleared'),900)}render();C.toast(first?`QUEST CLEAR · ${fmtHours(h)}의 증거 +${xp} XP`:`추가 공부 ${fmtHours(h)} 기록 완료 · XP 중복 보상 없음`)}
function createGoal(){let c=certs.find(x=>x.name===R.cert.value);if(!c)return C.toast('자격증을 선택해주세요.');let h=targetDaily(),exam=R.exam.value;if(h<=0)return C.toast('하루 목표 투자시간을 입력해주세요.');if(!exam)return C.toast('시험일을 선택해주세요.');let dd=dateDays(exam);if(dd!==null&&dd<0)return C.toast('시험일은 오늘 이후로 설정해주세요.');Q.long.filter(x=>!x.done).forEach(x=>x.paused=true);let stage=R.stage.value==='written'?'written':'practical',days=Math.max(1,(dd??0)+1);Q.long.push({id:`goal-${Date.now()}`,name:`${c.name} ${stage==='written'?'필기':'실기'}`,cert:c.name,stage,dailyHours:h,examDate:exam,days,targetHours:h*days,loggedHours:0,studyDays:0,started:today,attempts:[{examDate:exam,status:'preparing',createdAt:new Date().toISOString()}],done:false,paused:false});syncTarget(c.name,stage);R.builder.style.display='none';persist();render();C.toast('시험일까지의 집중 캠페인을 시작했습니다.')}
function updateExam(){let g=active(),v=el('activeExamDate')?.value;if(!g||!v)return;let old=g.examDate;if(old&&old!==v){g.attempts=g.attempts||[];let last=g.attempts[g.attempts.length-1];if(last&&last.examDate===old&&last.status==='preparing')last.status='rescheduled';g.attempts.push({examDate:v,status:'preparing',createdAt:new Date().toISOString()})}g.examDate=v;let dd=dateDays(v);g.days=Math.max(1,(dd??0)+1);g.targetHours=(+g.dailyHours||0)*g.days;persist();render();C.toast('시험일과 집중기간을 다시 계산했습니다.')}
function updateDailyTarget(){let g=active();if(!g)return;let h=Math.max(0,(+el('editDailyHours')?.value||0)+(+el('editDailyMinutes')?.value||0)/60);if(h<=0)return C.toast('목표 시간을 입력해주세요.');g.dailyHours=h;let dd=dateDays(g.examDate);g.days=Math.max(1,(dd??0)+1);g.targetHours=h*g.days;persist();render();C.toast('하루 목표 투자시간을 수정했습니다.')}
function openBuilder(){R.builder.style.display='block';let s=sessionStorage.getItem('lifeSpecupSuggestedCert');if(s&&certs.some(x=>x.name===s))R.cert.value=s;preview();R.builder.scrollIntoView({behavior:'smooth',block:'center'})}
function render(){let g=active(),d=day(),b=window.TargetBuild?TargetBuild.load():null,p=window.TargetBuild?TargetBuild.progress(b):0;R.day.textContent=`${today} · LIFE DAY`;R.build.innerHTML=b?`<div class="mini-build-score"><b>${p}%</b><span>미래 빌드 완성도</span></div><strong>${safe(b.name||'미래의 나')}</strong><p>${(b.certs||[]).length}개 자격 목표 · 경력 ${(+b.careerYears||0).toFixed(1)}년 목표</p>`:`<p>아직 미래 빌드가 없습니다.</p>`;
if(!g){R.core.innerHTML=`<h2>아직 오늘의 메인 퀘스트가 없습니다.</h2><p>먼저 현실 목표 하나를 연결하세요. 그 다음부터 앱이 오늘 해야 할 행동만 보여줍니다.</p><button class="primary" id="emptyStartBtn">첫 목표 연결</button>`;R.road.innerHTML='<div class="road-empty">목표를 시작하면 현실 단계가 여기에 이어집니다.</div>';R.active.innerHTML='<div class="empty">진행 중인 목표가 없습니다.</div>';R.rhythm.innerHTML='<div class="momentum-zero"><b>0</b><span>아직 첫 기록 전</span></div>';el('emptyStartBtn')?.addEventListener('click',openBuilder)}else{let target=Math.max(.01,+g.targetHours||1),pct=Math.min(100,Math.round((+g.loggedHours||0)/target*100)),done=!!d.simple?.done,total=todayTotal(d),daily=Math.max(.01,+g.dailyHours||2),dailyPct=Math.round(total/daily*100),dd=dateDays(g.examDate),remainDays=dd==null?null:Math.max(0,dd),remaining=Math.max(0,target-(+g.loggedHours||0)),needed=remainDays?remaining/remainDays:remaining;
let ready=C.readiness?C.readiness(g,Q.days):null;R.core.innerHTML=`<div class="quest-readiness-mini"><span>PASS READINESS</span><b>${ready?ready.score.toFixed(1):'--'}%</b><em class="${ready&&ready.delta<-.05?'down':'ok'}">${ready&&ready.delta<-.05?'▼ '+Math.abs(ready.delta).toFixed(1)+'%p':'ON TRACK'}</em></div><div class="mission-kicker"><span>${g.stage==='written'?'WRITTEN':'PRACTICAL'}</span><i>${pct}% CAMPAIGN</i></div><h2>${safe(g.cert)} <em>${g.stage==='written'?'필기':'실기'}</em></h2><p class="mission-why">오늘 목표 <b>${fmtHours(daily)}</b> · ${g.examDate?`시험까지 <b>${dd>=0?'D-'+dd:'경과'}</b>`:'시험일 미설정'}</p><div class="mission-progress"><span style="width:${Math.min(100,dailyPct)}%"></span></div>${done?`<div class="clear-banner"><span>✓</span><div><b>오늘의 증거 확보 · ${fmtHours(total)}</b><small>목표 ${fmtHours(daily)} · ${dailyPct}%${total>daily?` · +${fmtHours(total-daily)} 초과 투자`:''}</small></div></div><div class="extra-study"><div><b>더 공부했나요?</b><small>오늘은 끝나지 않습니다. 추가 공부는 계속 누적되고 XP는 중복 지급되지 않습니다.</small></div><div class="study-time-row"><input id="extraHours" type="number" min="0" max="23" step="1" value="0"><span>시간</span><input id="extraMinutes" type="number" min="0" max="59" step="5" value="30"><span>분</span><input id="extraNote" placeholder="추가 기록 (선택)"><button class="secondary" id="addStudyBtn">+ 공부 추가</button></div></div>`:`<div class="mission-action"><label><span>오늘 실제 공부</span><div class="study-time-row compact"><input id="todayHours" type="number" min="0" max="23" step="1" value="${Math.floor(daily)}"><span>시간</span><input id="todayMinutes" type="number" min="0" max="59" step="5" value="${Math.round((daily%1)*60)}"><span>분</span></div></label><label class="mission-note"><span>한 줄 기록 <i>선택</i></span><input id="todayNote" placeholder="예: 기출 2024년까지 진행"></label><button class="primary clear-btn" id="completeTodayBtn">QUEST CLEAR</button></div>`}<div class="pace-strip"><span>시험일까지 ${remainDays??'-'}일</span><span>누적 ${fmtHours(g.loggedHours||0)}</span><span>남은 목표 ${fmtHours(remaining)}</span><span>필요 페이스 ${fmtHours(needed)}/일</span></div>`;el('completeTodayBtn')?.addEventListener('click',()=>recordStudy(false));el('addStudyBtn')?.addEventListener('click',()=>recordStudy(true));
let stages=g.stage==='practical'?[['필기 합격',true,'현실 성취'],['실기 준비',true,`${g.studyDays||0}일 · ${fmtHours(g.loggedHours||0)}`],['실기 시험',false,g.examDate||'시험일 설정'],['최종 합격',false,'결과 확인'],['자격 취득',false,'BUILD COMPLETE']]:[['필기 준비',true,`${g.studyDays||0}일 · ${fmtHours(g.loggedHours||0)}`],['필기 시험',false,g.examDate||'시험일 설정'],['필기 합격',false,'결과 확인'],['실기 준비',false,'NEXT STAGE'],['자격 취득',false,'BUILD COMPLETE']];R.road.innerHTML=`<div class="road-line">${stages.map((x,i)=>`<div class="road-node ${x[1]?'active':''}"><span>${x[1]?'✓':i+1}</span><b>${x[0]}</b><small>${x[2]}</small></div>`).join('<i></i>')}</div>`;R.badge.textContent=`${pct}% 진행`;
let dh=Math.floor(daily),dm=Math.round((daily%1)*60);R.active.innerHTML=`<div class="campaign-card"><div><span class="badge">${g.stage==='written'?'필기':'실기'} CAMPAIGN</span><h3>${safe(g.cert)}</h3><p>${g.started} 시작 · ${g.studyDays||0}일 공부 · 누적 ${fmtHours(g.loggedHours||0)}</p></div><div class="campaign-stat"><b>${dd==null?'—':dd>=0?'D-'+dd:'종료'}</b><span>시험일까지 집중</span></div></div><div class="campaign-controls"><label><span>시험일</span><input id="activeExamDate" type="date" value="${g.examDate||''}"></label><button class="secondary smallbtn" id="saveExamDate">시험일 수정</button><label><span>하루 목표</span><div class="study-time-row compact"><input id="editDailyHours" type="number" min="0" max="23" value="${dh}"><span>h</span><input id="editDailyMinutes" type="number" min="0" max="59" step="5" value="${dm}"><span>m</span></div></label><button class="secondary smallbtn" id="saveDailyTarget">목표시간 수정</button></div>`;el('saveExamDate')?.addEventListener('click',updateExam);el('saveDailyTarget')?.addEventListener('click',updateDailyTarget);let doneDays=Object.values(Q.days).filter(x=>x.simple?.done).length;R.rhythm.innerHTML=`<div class="momentum"><div><b>${doneDays}</b><span>성장일</span></div><div><b>${g.studyDays||0}</b><span>이 목표 학습일</span></div><div><b>${fmtHours(g.loggedHours||0)}</b><span>누적 집중</span></div></div><p class="sub">체크 수가 아니라 실제로 투자한 시간이 쌓입니다.</p>`}
let hist=(S.history||[]).filter(x=>x.date).slice(0,10);R.history.innerHTML=hist.length?hist.map(x=>`<div class="journey-row"><span class="journey-dot"></span><div><b>${safe(x.text)}</b><small>${safe(x.date)}</small></div><strong>${(+x.xp||0)>0?'+'+(+x.xp||0)+' XP':'기록'}</strong></div>`).join(''):'<div class="empty">첫 QUEST CLEAR가 여기에 기록됩니다.</div>'}
function preview(){let h=targetDaily(),dd=dateDays(R.exam.value),days=dd==null?null:Math.max(1,dd+1);if(R.focus)R.focus.innerHTML=R.exam.value?`시험일까지 <strong>${Math.max(0,dd)}일</strong><small>${today} → ${R.exam.value}</small>`:'시험일을 선택하면 자동 계산';R.preview.innerHTML=`<b>${safe(R.cert.value)} · ${R.stage.value==='written'?'필기 준비':'필기 합격 → 실기 준비'}</b><p>하루 ${fmtHours(h)} · ${R.exam.value?`시험일 ${R.exam.value}까지 ${days}일 집중 · 계획 투자 ${fmtHours(h*days)}`:'시험일을 선택하면 집중기간과 총 투자시간을 자동 계산합니다.'}</p>`}
R.cert.innerHTML=certs.map(x=>`<option value="${safe(x.name)}">${safe(x.name)}</option>`).join('');el('newGoalBtn').addEventListener('click',openBuilder);el('closeBuilder').addEventListener('click',()=>R.builder.style.display='none');el('createGoal').addEventListener('click',createGoal);[R.cert,R.stage,R.hours,R.mins,R.exam].forEach(x=>x?.addEventListener('input',preview));preview();render();})();
